//! Replays `fixtures/plugin_routes_go.json` (generated by `reference/plugins` from a
//! complete Go management server with a real plugin host at 6fecc6e) against the Rust
//! management router with the same c-shared plugins: plugin list, config reads and
//! writes, enable, delete, and plugin-declared routes and resources through NoRoute.

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use cpa_core::config::Config;
use cpa_exec::Executors;
use cpa_exec::claude::ClaudeExecutor;
use cpa_server::management::{self, Management, Options};
use serde_json::Value;

struct Dirs {
    plugins: PathBuf,
    records: PathBuf,
    config: PathBuf,
}

impl Dirs {
    fn placeholders(&self, s: &str) -> String {
        s.replace("PLUGINDIR", &self.plugins.to_string_lossy())
            .replace("RECORDDIR", &self.records.to_string_lossy())
    }

    fn normalize(&self, s: &str) -> String {
        s.replace(&*self.plugins.to_string_lossy(), "PLUGINDIR")
            .replace(&*self.records.to_string_lossy(), "RECORDDIR")
    }
}

/// The binary's app (API routes, then management and its NoRoute) with every request
/// coming from `127.0.0.1:40000`.
async fn serve(rt: Arc<cpa_server::Runtime>, state: Arc<Management>) -> String {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}", listener.local_addr().unwrap());
    let app = cpa_server::app(rt, management::router(state)).layer(axum::middleware::from_fn(
        |mut req: axum::extract::Request, next: axum::middleware::Next| async move {
            let peer: SocketAddr = "127.0.0.1:40000".parse().unwrap();
            req.extensions_mut().insert(axum::extract::ConnectInfo(peer));
            next.run(req).await
        },
    ));
    tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
    base
}

async fn start(dirs: &Dirs, yaml: &str) -> String {
    let hash = bcrypt::hash("fake-secret", 4).unwrap();
    std::fs::write(&dirs.config, dirs.placeholders(yaml).replace("$HASH", &hash)).unwrap();
    let rt = Arc::new(cpa_server::testing::runtime(
        Config::load(&dirs.config).unwrap(),
        vec![],
        Executors {
            claude: ClaudeExecutor::new("http://127.0.0.1:1").unwrap(),
            codex: Default::default(),
            devices: Default::default(),
            openai: Default::default(),
            google: Default::default(),
        },
    ));
    let state = Management::with_options(rt.clone(), dirs.config.clone(), Options::default());
    cpa_server::plugins::start(&rt).await;
    serve(rt, state).await
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn plugin_routes_match_go() {
    let tmp = Path::new(env!("CARGO_TARGET_TMPDIR"));
    let Some(built) = cpa_plugin::testing::built_plugins(tmp, "plugin_routes::plugin_routes_match_go") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/plugin_routes_go.json")).unwrap();
    let work = cpa_plugin::testing::scratch(tmp, "plugin-routes");
    let dirs = Dirs {
        plugins: work.join("plugins"),
        records: work.join("records"),
        config: work.join("config.yaml"),
    };
    std::fs::create_dir_all(&dirs.plugins).unwrap();
    std::fs::create_dir_all(&dirs.records).unwrap();
    let client = wreq::Client::new();
    let mut base = String::new();
    let mut failures = Vec::new();
    for (i, step) in fixture["steps"].as_array().unwrap().iter().enumerate() {
        let args = &step["args"];
        let got = match step["op"].as_str().unwrap() {
            "files" => {
                for (name, from) in args.as_object().unwrap() {
                    let from = built.join(format!("{}.so", from.as_str().unwrap()));
                    std::fs::copy(from, dirs.plugins.join(name)).unwrap();
                }
                Value::Null
            }
            "config" => {
                base = start(&dirs, args.as_str().unwrap()).await;
                Value::Null
            }
            "settle" => {
                tokio::time::sleep(std::time::Duration::from_millis(700)).await;
                Value::Null
            }
            "plugins" => {
                let text = std::fs::read_to_string(&dirs.config).unwrap();
                let doc: serde_yaml_ng::Value = serde_yaml_ng::from_str(&text).unwrap();
                let plugins = serde_json::to_string(&doc["plugins"]).unwrap();
                serde_json::from_str(&dirs.normalize(&plugins)).unwrap()
            }
            "http" => {
                let method = wreq::Method::from_bytes(args["method"].as_str().unwrap().as_bytes()).unwrap();
                let body = dirs.placeholders(args["body"].as_str().unwrap_or_default());
                let mut req = client
                    .request(method, format!("{base}{}", args["path"].as_str().unwrap()))
                    .body(body);
                if !args["no_key"].as_bool().unwrap_or(false) {
                    req = req.header("Authorization", "Bearer fake-secret");
                }
                let res = req.send().await.unwrap();
                let status = res.status().as_u16();
                let content_type = res
                    .headers()
                    .get("content-type")
                    .map(|v| v.to_str().unwrap().to_owned())
                    .unwrap_or_default();
                let version = res.headers().contains_key("x-cpa-version");
                let text = res.text().await.unwrap();
                serde_json::json!({
                    "status": status,
                    "content_type": content_type,
                    "body": dirs.normalize(&text),
                    "version_headers": version,
                })
            }
            other => panic!("unknown step {other}"),
        };
        if step["result"] != got {
            failures.push(format!(
                "step {i} {} {}\n  go:   {}\n  rust: {}",
                step["op"], args, step["result"], got
            ));
        }
    }
    let _ = std::fs::remove_dir_all(&work);
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
