//! Replays `fixtures/plugin_routes_go.json` (generated by `reference/plugins` from a
//! complete Go management server with a real plugin host at 6fecc6e) against the Rust
//! management router with the same c-shared plugins: plugin list, config reads and
//! writes, enable, delete, and plugin-declared routes and resources through NoRoute.

// Native plugins load only on Unix (the host's `native` module).
#![cfg(unix)]

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use cpa_core::config::Config;
use cpa_exec::Executors;
use cpa_exec::claude::ClaudeExecutor;
use cpa_server::management::{self, Management, Options};
use serde_json::Value;

struct Dirs {
    plugins: PathBuf,
    records: PathBuf,
    auths: PathBuf,
    config: PathBuf,
    /// Auth file name to its `auth_index`.
    indexes: std::sync::Mutex<Vec<(String, String)>>,
}

impl Dirs {
    fn placeholders(&self, s: &str) -> String {
        let mut s = s
            .replace("PLUGINDIR", &self.plugins.to_string_lossy())
            .replace("RECORDDIR", &self.records.to_string_lossy())
            .replace("AUTHDIR", &self.auths.to_string_lossy());
        for (name, index) in self.indexes.lock().unwrap().iter() {
            s = s.replace(&format!("AUTHINDEX({name})"), index);
        }
        s
    }

    fn normalize(&self, s: &str) -> String {
        let mut s = s
            .replace(&*self.plugins.to_string_lossy(), "PLUGINDIR")
            .replace(&*self.records.to_string_lossy(), "RECORDDIR")
            .replace(&*self.auths.to_string_lossy(), "AUTHDIR");
        for (name, index) in self.indexes.lock().unwrap().iter() {
            s = s.replace(index, &format!("AUTHINDEX({name})"));
        }
        s
    }

    /// The quota.* calls the recorders received since the last call, normalized as the
    /// generator does (callback context IDs are opaque counters).
    fn records(&self) -> Value {
        let mut out = Vec::new();
        let mut files: Vec<_> = std::fs::read_dir(&self.records)
            .unwrap()
            .map(|e| e.unwrap().path())
            .filter(|p| p.is_file())
            .collect();
        files.sort();
        for path in files {
            let label = path.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&path).unwrap();
            std::fs::remove_file(&path).unwrap();
            for line in text.lines() {
                let rec: Value = serde_json::from_str(line).unwrap();
                let method = rec["method"].as_str().unwrap();
                if !method.starts_with("quota.") {
                    continue;
                }
                let request = self.normalize(rec["request"].as_str().unwrap());
                let request = regex_lite_callback(&request);
                out.push(serde_json::json!({"label": label, "method": method, "request": request}));
            }
        }
        Value::Array(out)
    }
}

/// `"host_callback_id":"<digits>"` as `"host_callback_id":"#"`.
fn regex_lite_callback(s: &str) -> String {
    const KEY: &str = "\"host_callback_id\":\"";
    let mut out = String::new();
    let mut rest = s;
    while let Some(at) = rest.find(KEY) {
        out.push_str(&rest[..at + KEY.len()]);
        rest = rest[at + KEY.len()..].trim_start_matches(|c: char| c.is_ascii_digit());
        out.push('#');
    }
    out.push_str(rest);
    out
}

/// The binary's app (API routes, then management and its NoRoute) with every request
/// coming from `127.0.0.1:40000`.
async fn serve(rt: Arc<cpa_server::Runtime>, state: Arc<Management>) -> String {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}", listener.local_addr().unwrap());
    let app = cpa_server::app(rt, management::router(state)).layer(axum::middleware::from_fn(
        |mut req: axum::extract::Request, next: axum::middleware::Next| async move {
            let peer: SocketAddr = "127.0.0.1:40000".parse().unwrap();
            req.extensions_mut().insert(axum::extract::ConnectInfo(peer));
            next.run(req).await
        },
    ));
    tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
    base
}

async fn start(dirs: &Dirs, yaml: &str) -> String {
    let hash = bcrypt::hash("fake-secret", 4).unwrap();
    std::fs::write(&dirs.config, dirs.placeholders(yaml).replace("$HASH", &hash)).unwrap();
    let config = Config::load(&dirs.config).unwrap();
    let credentials = cpa_core::config::credentials::load(&config);
    *dirs.indexes.lock().unwrap() = credentials
        .iter()
        .filter_map(|c| match &c.source {
            cpa_core::credential::Source::File(path) => Some((
                path.file_name()?.to_string_lossy().into_owned(),
                cpa_core::config::credentials::auth_index(c),
            )),
            _ => None,
        })
        .collect();
    let rt = Arc::new(cpa_server::testing::runtime(
        config,
        credentials,
        Executors {
            claude: ClaudeExecutor::new("http://127.0.0.1:1").unwrap(),
            codex: Default::default(),
            devices: Default::default(),
            openai: Default::default(),
            google: Default::default(),
        },
    ));
    let state = Management::with_options(rt.clone(), dirs.config.clone(), Options::default());
    cpa_server::plugins::start(&rt).await;
    serve(rt, state).await
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn plugin_routes_match_go() {
    let tmp = Path::new(env!("CARGO_TARGET_TMPDIR"));
    let Some(built) = cpa_plugin::testing::built_plugins(tmp, "plugin_routes::plugin_routes_match_go") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/plugin_routes_go.json")).unwrap();
    let work = cpa_plugin::testing::scratch(tmp, "plugin-routes");
    let dirs = Dirs {
        plugins: work.join("plugins"),
        records: work.join("records"),
        auths: work.join("auths"),
        config: work.join("config.yaml"),
        indexes: Default::default(),
    };
    std::fs::create_dir_all(&dirs.plugins).unwrap();
    std::fs::create_dir_all(&dirs.records).unwrap();
    std::fs::create_dir_all(&dirs.auths).unwrap();
    let client = wreq::Client::new();
    let mut base = String::new();
    let mut failures = Vec::new();
    for (i, step) in fixture["steps"].as_array().unwrap().iter().enumerate() {
        let args = &step["args"];
        let got = match step["op"].as_str().unwrap() {
            "files" => {
                for (name, from) in args.as_object().unwrap() {
                    let from = built.join(format!("{}.so", from.as_str().unwrap()));
                    std::fs::copy(from, dirs.plugins.join(name)).unwrap();
                }
                Value::Null
            }
            "config" => {
                base = start(&dirs, args.as_str().unwrap()).await;
                Value::Null
            }
            "auths" => {
                for (name, body) in args.as_object().unwrap() {
                    std::fs::write(dirs.auths.join(name), body.as_str().unwrap()).unwrap();
                }
                Value::Null
            }
            "respond" => {
                let dir = dirs.records.join("respond").join(args["label"].as_str().unwrap());
                std::fs::create_dir_all(&dir).unwrap();
                let path = dir.join(format!("{}.json", args["method"].as_str().unwrap()));
                match args["envelope"].as_str().unwrap() {
                    "" => {
                        let _ = std::fs::remove_file(path);
                    }
                    envelope => std::fs::write(path, envelope).unwrap(),
                }
                Value::Null
            }
            "records" => dirs.records(),
            "settle" => {
                tokio::time::sleep(std::time::Duration::from_millis(700)).await;
                Value::Null
            }
            "plugins" => {
                let text = std::fs::read_to_string(&dirs.config).unwrap();
                let doc: serde_yaml_ng::Value = serde_yaml_ng::from_str(&text).unwrap();
                let plugins = serde_json::to_string(&doc["plugins"]).unwrap();
                serde_json::from_str(&dirs.normalize(&plugins)).unwrap()
            }
            "http" => {
                let method = wreq::Method::from_bytes(args["method"].as_str().unwrap().as_bytes()).unwrap();
                let body = dirs.placeholders(args["body"].as_str().unwrap_or_default());
                let mut req = client
                    .request(
                        method,
                        format!("{base}{}", dirs.placeholders(args["path"].as_str().unwrap())),
                    )
                    .body(body);
                if !args["no_key"].as_bool().unwrap_or(false) {
                    req = req.header("Authorization", "Bearer fake-secret");
                }
                let res = req.send().await.unwrap();
                let status = res.status().as_u16();
                let content_type = res
                    .headers()
                    .get("content-type")
                    .map(|v| v.to_str().unwrap().to_owned())
                    .unwrap_or_default();
                let version = res.headers().contains_key("x-cpa-version");
                let text = res.text().await.unwrap();
                serde_json::json!({
                    "status": status,
                    "content_type": content_type,
                    "body": dirs.normalize(&text),
                    "version_headers": version,
                })
            }
            other => panic!("unknown step {other}"),
        };
        if step["result"] != got {
            failures.push(format!(
                "step {i} {} {}\n  go:   {}\n  rust: {}",
                step["op"], args, step["result"], got
            ));
        }
    }
    let _ = std::fs::remove_dir_all(&work);
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
