//! Replays `fixtures/plugin_routes_go.json` (generated by `reference/plugins` from a
//! complete Go management server with a real plugin host at 6fecc6e) against the Rust
//! management router with the same c-shared plugins: plugin list, config reads and
//! writes, enable, delete, plugin-declared routes and resources through NoRoute, quota,
//! and the plugin store through a fake HTTP client (every request it receives compared).

// Native plugins load only on Unix (the host's `native` module).
#![cfg(unix)]

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use cpa_core::config::Config;
use cpa_exec::Executors;
use cpa_exec::claude::ClaudeExecutor;
use cpa_server::management::{self, Management, Options};
use serde_json::Value;
use sha2::Digest as _;

/// The generator's `storeDoer`: fixed routes by exact URL, every request recorded.
/// Bodies name a zip route's digest as `ZIPSHA(<url>)`.
struct StoreDoer {
    built: PathBuf,
    routes: std::sync::Mutex<serde_json::Map<String, Value>>,
    requests: std::sync::Mutex<Vec<Value>>,
}

impl StoreDoer {
    fn zip(&self, entries: &Value) -> Vec<u8> {
        let files: Vec<(String, Vec<u8>, u32)> = entries
            .as_array()
            .unwrap()
            .iter()
            .map(|e| match e["plugin"].as_str() {
                Some(plugin) => (
                    e["name"].as_str().unwrap().to_owned(),
                    std::fs::read(self.built.join(format!("{plugin}.so"))).unwrap(),
                    0o755,
                ),
                None => (
                    e["name"].as_str().unwrap().to_owned(),
                    e["data"].as_str().unwrap_or_default().as_bytes().to_vec(),
                    0,
                ),
            })
            .collect();
        let refs: Vec<(&str, &[u8], u32)> = files.iter().map(|(n, d, m)| (n.as_str(), d.as_slice(), *m)).collect();
        cpa_plugin::testing::stored_zip(&refs)
    }

    fn digest(&self, entries: &Value) -> String {
        sha2::Sha256::digest(self.zip(entries))
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect()
    }

    /// Each zip route's digest and its `ZIPSHA(<url>)` placeholder.
    fn digests(&self) -> Vec<(String, String)> {
        let routes = self.routes.lock().unwrap().clone();
        routes
            .iter()
            .filter(|(_, r)| r.get("zip").is_some())
            .map(|(url, r)| (self.digest(&r["zip"]), format!("ZIPSHA({url})")))
            .collect()
    }
}

impl cpa_plugin::store::Doer for StoreDoer {
    fn get(
        &self,
        url: &str,
        headers: &cpa_plugin::store::Headers,
    ) -> futures_util::future::BoxFuture<'_, Result<cpa_plugin::store::DoerResponse, String>> {
        self.requests
            .lock()
            .unwrap()
            .push(serde_json::json!({"url": url, "headers": headers}));
        let routes = self.routes.lock().unwrap().clone();
        let result = match routes.get(url) {
            None => Err(format!("no route for {url}")),
            Some(route) => {
                let body = match route.get("zip") {
                    Some(zip) => self.zip(zip),
                    None => {
                        let mut text = route["body"].as_str().unwrap_or_default().to_owned();
                        while let Some(at) = text.find("ZIPSHA(") {
                            let end = at + text[at..].find(')').unwrap();
                            let digest = self.digest(&routes[&text[at + 7..end]]["zip"]);
                            text.replace_range(at..=end, &digest);
                        }
                        text.into_bytes()
                    }
                };
                // Go's http.Header.Set: canonical keys.
                let mut headers = cpa_plugin::store::Headers::new();
                for (name, value) in route["headers"].as_object().into_iter().flatten() {
                    headers.insert(
                        cpa_exec::proxy::canonical_header(name),
                        vec![value.as_str().unwrap().to_owned()],
                    );
                }
                Ok(cpa_plugin::store::DoerResponse {
                    status: route["status"].as_u64().unwrap() as u16,
                    headers,
                    body: Box::pin(futures_util::stream::once(
                        async move { Ok(axum::body::Bytes::from(body)) },
                    )),
                })
            }
        };
        Box::pin(async move { result })
    }
}

/// The generator's `stableBody`: the seconds until a far-future rate-limit reset.
fn stable_body(body: &str) -> String {
    const KEY: &str = "\"retry_after\":";
    let mut out = String::new();
    let mut rest = body;
    while let Some(at) = rest.find(KEY) {
        out.push_str(&rest[..at + KEY.len()]);
        let digits = rest[at + KEY.len()..].trim_start_matches(|c: char| c.is_ascii_digit());
        if digits.len() < rest.len() - at - KEY.len() {
            out.push('N');
        }
        rest = digits;
    }
    out.push_str(rest);
    out
}

/// The quota probe's upstream (the generator's httptest server): fixed answers by
/// path, every request recorded as Go's handler sees it (canonical header names,
/// without Host and Content-Length).
#[derive(Default)]
struct Upstream {
    base: std::sync::Mutex<String>,
    seen: Arc<std::sync::Mutex<Vec<Value>>>,
}

impl Upstream {
    async fn start(&self, routes: Value) {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        *self.base.lock().unwrap() = format!("http://{}", listener.local_addr().unwrap());
        let seen = self.seen.clone();
        tokio::spawn(async move {
            loop {
                let Ok((mut stream, _)) = listener.accept().await else {
                    return;
                };
                let (routes, seen) = (routes.clone(), seen.clone());
                tokio::spawn(async move {
                    let mut buf = Vec::new();
                    let head_end = loop {
                        let mut chunk = [0u8; 4096];
                        let n = stream.read(&mut chunk).await.unwrap_or(0);
                        if n == 0 {
                            return;
                        }
                        buf.extend_from_slice(&chunk[..n]);
                        if let Some(i) = buf.windows(4).position(|w| w == b"\r\n\r\n") {
                            break i;
                        }
                    };
                    let head = String::from_utf8_lossy(&buf[..head_end]).into_owned();
                    let mut lines = head.split("\r\n");
                    let mut request_line = lines.next().unwrap().split(' ');
                    let (method, uri) = (
                        request_line.next().unwrap().to_owned(),
                        request_line.next().unwrap().to_owned(),
                    );
                    let mut header = serde_json::Map::new();
                    let mut length = 0usize;
                    let mut host = String::new();
                    for line in lines {
                        let (name, value) = line.split_once(':').unwrap();
                        let name = cpa_exec::proxy::canonical_header(name.trim());
                        let value = value.trim().to_owned();
                        if name == "Content-Length" {
                            length = value.parse().unwrap();
                            continue;
                        }
                        if name == "Host" {
                            host = value;
                            continue;
                        }
                        header
                            .entry(name)
                            .or_insert_with(|| Value::Array(Vec::new()))
                            .as_array_mut()
                            .unwrap()
                            .push(value.into());
                    }
                    let mut body = buf[head_end + 4..].to_vec();
                    while body.len() < length {
                        let mut chunk = [0u8; 4096];
                        let n = stream.read(&mut chunk).await.unwrap_or(0);
                        if n == 0 {
                            break;
                        }
                        body.extend_from_slice(&chunk[..n]);
                    }
                    let path = uri.split('?').next().unwrap_or_default().to_owned();
                    seen.lock().unwrap().push(serde_json::json!({
                        "method": method, "uri": uri, "host": host, "header": header, "body": String::from_utf8_lossy(&body),
                    }));
                    let route = &routes[path.as_str()];
                    let (status, text) = match route["Status"].as_u64() {
                        Some(s) => (s, route["Body"].as_str().unwrap_or_default().to_owned()),
                        None => (404, String::new()),
                    };
                    let mut response = format!(
                        "HTTP/1.1 {status} X\r\nContent-Length: {}\r\nConnection: close\r\n",
                        text.len()
                    );
                    if let Some(location) = route["Location"].as_str().filter(|l| !l.is_empty()) {
                        response.push_str(&format!("Location: {location}\r\n"));
                    }
                    response.push_str("\r\n");
                    response.push_str(&text);
                    let _ = stream.write_all(response.as_bytes()).await;
                    let _ = stream.shutdown().await;
                });
            }
        });
    }
}

struct Dirs {
    plugins: PathBuf,
    records: PathBuf,
    auths: PathBuf,
    config: PathBuf,
    /// Auth file name to its `auth_index`.
    indexes: std::sync::Mutex<Vec<(String, String)>>,
    store: Arc<StoreDoer>,
    upstream: Upstream,
}

impl Dirs {
    fn placeholders(&self, s: &str) -> String {
        let mut s = s
            .replace("PLUGINDIR", &self.plugins.to_string_lossy())
            .replace("RECORDDIR", &self.records.to_string_lossy())
            .replace("AUTHDIR", &self.auths.to_string_lossy());
        for (name, index) in self.indexes.lock().unwrap().iter() {
            s = s.replace(&format!("AUTHINDEX({name})"), index);
        }
        let upstream = self.upstream.base.lock().unwrap().clone();
        if !upstream.is_empty() {
            s = s.replace("UPSTREAM", &upstream);
        }
        s
    }

    fn normalize(&self, s: &str) -> String {
        let mut s = s
            .replace(&*self.plugins.to_string_lossy(), "PLUGINDIR")
            .replace(&*self.records.to_string_lossy(), "RECORDDIR")
            .replace(&*self.auths.to_string_lossy(), "AUTHDIR");
        for (name, index) in self.indexes.lock().unwrap().iter() {
            s = s.replace(index, &format!("AUTHINDEX({name})"));
        }
        for (digest, placeholder) in self.store.digests() {
            s = s.replace(&digest, &placeholder);
        }
        let upstream = self.upstream.base.lock().unwrap().clone();
        if !upstream.is_empty() {
            s = s.replace(&upstream, "UPSTREAM");
            s = s.replace(upstream.trim_start_matches("http://"), "UPSTREAMHOST");
        }
        s
    }

    /// The quota.* calls the recorders received since the last call, normalized as the
    /// generator does (callback context IDs are opaque counters).
    fn records(&self) -> Value {
        let mut out = Vec::new();
        let mut files: Vec<_> = std::fs::read_dir(&self.records)
            .unwrap()
            .map(|e| e.unwrap().path())
            .filter(|p| p.is_file())
            .collect();
        files.sort();
        for path in files {
            let label = path.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&path).unwrap();
            std::fs::remove_file(&path).unwrap();
            for line in text.lines() {
                let rec: Value = serde_json::from_str(line).unwrap();
                let method = rec["method"].as_str().unwrap();
                if !method.starts_with("quota.") && !method.starts_with("auth.login.") {
                    continue;
                }
                let request = self.normalize(rec["request"].as_str().unwrap());
                let request = regex_lite_callback(&request);
                out.push(serde_json::json!({"label": label, "method": method, "request": request}));
            }
        }
        Value::Array(out)
    }
}

/// `"host_callback_id":"<digits>"` as `"host_callback_id":"#"`.
fn regex_lite_callback(s: &str) -> String {
    const KEY: &str = "\"host_callback_id\":\"";
    let mut out = String::new();
    let mut rest = s;
    while let Some(at) = rest.find(KEY) {
        out.push_str(&rest[..at + KEY.len()]);
        rest = rest[at + KEY.len()..].trim_start_matches(|c: char| c.is_ascii_digit());
        out.push('#');
    }
    out.push_str(rest);
    out
}

/// The binary's app (API routes, then management and its NoRoute) with every request
/// coming from `127.0.0.1:40000`.
async fn serve(rt: Arc<cpa_server::Runtime>, state: Arc<Management>) -> String {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let base = format!("http://{}", listener.local_addr().unwrap());
    let app = cpa_server::app(rt, management::router(state)).layer(axum::middleware::from_fn(
        |mut req: axum::extract::Request, next: axum::middleware::Next| async move {
            let peer: SocketAddr = "127.0.0.1:40000".parse().unwrap();
            req.extensions_mut().insert(axum::extract::ConnectInfo(peer));
            next.run(req).await
        },
    ));
    tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
    base
}

async fn start(dirs: &Dirs, yaml: &str) -> String {
    let hash = bcrypt::hash("fake-secret", 4).unwrap();
    std::fs::write(&dirs.config, dirs.placeholders(yaml).replace("$HASH", &hash)).unwrap();
    let config = Config::load(&dirs.config).unwrap();
    let credentials = cpa_core::config::credentials::load(&config);
    *dirs.indexes.lock().unwrap() = credentials
        .iter()
        .filter_map(|c| match &c.source {
            cpa_core::credential::Source::File(path) => Some((
                path.file_name()?.to_string_lossy().into_owned(),
                cpa_core::config::credentials::auth_index(c),
            )),
            _ => None,
        })
        .collect();
    let rt = Arc::new(cpa_server::testing::runtime(
        config,
        credentials,
        Executors {
            claude: ClaudeExecutor::new("http://127.0.0.1:1").unwrap(),
            codex: Default::default(),
            devices: Default::default(),
            openai: Default::default(),
            google: Default::default(),
        },
    ));
    let state = Management::with_options(
        rt.clone(),
        dirs.config.clone(),
        Options {
            plugin_store_http: Some(dirs.store.clone()),
            plugin_store_rate_limiter: Some(Default::default()),
            ..Options::default()
        },
    );
    cpa_server::plugins::start(&rt).await;
    serve(rt, state).await
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn plugin_routes_match_go() {
    let tmp = Path::new(env!("CARGO_TARGET_TMPDIR"));
    let Some(built) = cpa_plugin::testing::built_plugins(tmp, "plugin_routes::plugin_routes_match_go") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/plugin_routes_go.json")).unwrap();
    let work = cpa_plugin::testing::scratch(tmp, "plugin-routes");
    let dirs = Dirs {
        plugins: work.join("plugins"),
        records: work.join("records"),
        auths: work.join("auths"),
        config: work.join("config.yaml"),
        indexes: Default::default(),
        store: Arc::new(StoreDoer {
            built: built.to_path_buf(),
            routes: Default::default(),
            requests: Default::default(),
        }),
        upstream: Upstream::default(),
    };
    // SAFETY: the only test in this binary; set before any server starts.
    unsafe { std::env::set_var("CPA_STORE_ROUTES_TOKEN", "store-token") };
    std::fs::create_dir_all(&dirs.plugins).unwrap();
    std::fs::create_dir_all(&dirs.records).unwrap();
    std::fs::create_dir_all(&dirs.auths).unwrap();
    let client = wreq::Client::new();
    let mut base = String::new();
    let mut failures = Vec::new();
    for (i, step) in fixture["steps"].as_array().unwrap().iter().enumerate() {
        let args = &step["args"];
        let got = match step["op"].as_str().unwrap() {
            "files" => {
                for (name, from) in args.as_object().unwrap() {
                    let from = built.join(format!("{}.so", from.as_str().unwrap()));
                    std::fs::copy(from, dirs.plugins.join(name)).unwrap();
                }
                Value::Null
            }
            "config" => {
                base = start(&dirs, args.as_str().unwrap()).await;
                Value::Null
            }
            "auths" => {
                use std::os::unix::fs::PermissionsExt as _;
                for (name, body) in args.as_object().unwrap() {
                    let path = dirs.auths.join(name);
                    std::fs::write(&path, dirs.placeholders(body.as_str().unwrap())).unwrap();
                    // The generator writes them 0600.
                    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
                }
                Value::Null
            }
            "respond" => {
                let dir = dirs.records.join("respond").join(args["label"].as_str().unwrap());
                std::fs::create_dir_all(&dir).unwrap();
                let path = dir.join(format!("{}.json", args["method"].as_str().unwrap()));
                match args["envelope"].as_str().unwrap() {
                    "" => {
                        let _ = std::fs::remove_file(path);
                    }
                    envelope => std::fs::write(path, envelope).unwrap(),
                }
                Value::Null
            }
            "records" => dirs.records(),
            "upstream" => {
                dirs.upstream.start(args.clone()).await;
                Value::Null
            }
            "upstream_requests" => {
                let seen = std::mem::take(&mut *dirs.upstream.seen.lock().unwrap());
                serde_json::from_str(&dirs.normalize(&Value::Array(seen).to_string())).unwrap()
            }
            "auth_files" => {
                use std::os::unix::fs::PermissionsExt as _;
                let mut out = serde_json::Map::new();
                let mut names: Vec<_> = std::fs::read_dir(&dirs.auths)
                    .unwrap()
                    .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
                    .collect();
                names.sort();
                for name in names {
                    let path = dirs.auths.join(&name);
                    let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
                    let body = dirs.normalize(&std::fs::read_to_string(&path).unwrap());
                    out.insert(name, format!("{mode:o} {body}").into());
                }
                Value::Object(out)
            }
            "store_routes" => {
                *dirs.store.routes.lock().unwrap() = args.as_object().unwrap().clone();
                Value::Null
            }
            "store_requests" => {
                let mut requests = std::mem::take(&mut *dirs.store.requests.lock().unwrap());
                requests.sort_by(|a, b| a["url"].as_str().cmp(&b["url"].as_str()));
                Value::Array(requests)
            }
            "settle" => {
                tokio::time::sleep(std::time::Duration::from_millis(700)).await;
                Value::Null
            }
            "plugins" => {
                let text = std::fs::read_to_string(&dirs.config).unwrap();
                let doc: serde_yaml_ng::Value = serde_yaml_ng::from_str(&text).unwrap();
                let plugins = serde_json::to_string(&doc["plugins"]).unwrap();
                serde_json::from_str(&dirs.normalize(&plugins)).unwrap()
            }
            "http" => {
                let method = wreq::Method::from_bytes(args["method"].as_str().unwrap().as_bytes()).unwrap();
                let body = dirs.placeholders(args["body"].as_str().unwrap_or_default());
                let mut req = client
                    .request(
                        method,
                        format!("{base}{}", dirs.placeholders(args["path"].as_str().unwrap())),
                    )
                    .body(body);
                if !args["no_key"].as_bool().unwrap_or(false) {
                    req = req.header("Authorization", "Bearer fake-secret");
                }
                let res = req.send().await.unwrap();
                let status = res.status().as_u16();
                let content_type = res
                    .headers()
                    .get("content-type")
                    .map(|v| v.to_str().unwrap().to_owned())
                    .unwrap_or_default();
                let version = res.headers().contains_key("x-cpa-version");
                let text = res.text().await.unwrap();
                serde_json::json!({
                    "status": status,
                    "content_type": content_type,
                    "body": stable_body(&dirs.normalize(&text)),
                    "version_headers": version,
                })
            }
            other => panic!("unknown step {other}"),
        };
        if step["result"] != got {
            failures.push(format!(
                "step {i} {} {}\n  go:   {}\n  rust: {}",
                step["op"], args, step["result"], got
            ));
        }
    }
    let _ = std::fs::remove_dir_all(&work);
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
