//! Replays `fixtures/pluginhost_go.json` (generated by `reference/pluginhost` from the Go
//! plugin host at 6fecc6e) against the Rust host with the same c-shared plugins and
//! compares every observable: registered plugins and their order, load state, the
//! management and resource route tables and responses, host callback answers, and the
//! exact request bytes every plugin received (config YAML compared as YAML, since the
//! emitters format differently).

// Native plugins load only on Unix (the host's `native` module).
#![cfg(unix)]

#[path = "go_host/auth.rs"]
mod auth;
#[path = "go_host/calls.rs"]
mod calls;
mod support;

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use bytes::Bytes;
use cpa_plugin::Host;
use cpa_plugin::gojson::Header;
use cpa_plugin::management::Inbound;
use serde_json::{Value, json};

struct Runner {
    built: PathBuf,
    plugin_dir: PathBuf,
    record_dir: PathBuf,
    auth_dir: PathBuf,
    /// host:port of the raw upstream (`cpa_plugin::testing::raw_upstream`).
    upstream: String,
    host: Host,
}

impl Runner {
    fn placeholders(&self, text: &str) -> String {
        text.replace("PLUGINDIR", &self.plugin_dir.to_string_lossy())
            .replace("RECORDDIR", &self.record_dir.to_string_lossy())
            .replace("AUTHDIR", &self.auth_dir.to_string_lossy())
    }

    fn registered(&self) -> Value {
        Value::Array(
            self.host
                .registered_plugins()
                .into_iter()
                .map(|info| {
                    let metadata: Value = serde_json::from_slice(&cpa_plugin::gojson::to_vec(&info.metadata)).unwrap();
                    json!({
                        "id": info.id,
                        "priority": info.priority,
                        "metadata": metadata,
                        "supports_oauth": info.supports_oauth,
                        "oauth_provider": info.oauth_provider,
                        "supports_quota": info.supports_quota,
                        "quota_provider": info.quota_provider,
                        "menus": info.menus.iter().map(|m| json!({"path": m.path, "menu": m.menu, "description": m.description})).collect::<Vec<_>>(),
                    })
                })
                .collect(),
        )
    }

    async fn step(&self, op: &str, args: &Value) -> Value {
        match op {
            "files" => {
                for (name, from) in args.as_object().unwrap() {
                    let from = self.built.join(format!("{}.so", from.as_str().unwrap()));
                    std::fs::copy(from, self.plugin_dir.join(name)).unwrap();
                }
                Value::Null
            }
            "apply" => {
                let cfg = cpa_core::config::Config::parse(&self.placeholders(args.as_str().unwrap())).unwrap();
                self.host.apply_config(Arc::new(cfg)).await;
                self.registered()
            }
            "loaded" => {
                let mut out = serde_json::Map::new();
                for id in args.as_array().unwrap() {
                    let id = id.as_str().unwrap();
                    out.insert(
                        id.into(),
                        json!([self.host.plugin_loaded(id), self.host.plugin_registered(id)]),
                    );
                }
                Value::Object(out)
            }
            "register_management" => {
                // Go's empty variadic list marshals as null.
                let reserved: HashSet<String> = args
                    .as_array()
                    .into_iter()
                    .flatten()
                    .map(|v| v.as_str().unwrap().to_owned())
                    .collect();
                self.host.register_management_routes(&reserved).await;
                self.registered()
            }
            "management" | "resource" => {
                let target = args["target"].as_str().unwrap();
                let (path, query) = target.split_once('?').unwrap_or((target, ""));
                let mut q = Header::new();
                for (k, v) in url::form_urlencoded::parse(query.as_bytes()) {
                    q.entry(k.into_owned()).or_default().push(v.into_owned());
                }
                let mut headers = Header::new();
                if let Some(h) = args.get("headers").and_then(Value::as_object) {
                    for (k, vs) in h {
                        for v in vs.as_array().unwrap() {
                            headers
                                .entry(cpa_exec::proxy::canonical_header(k))
                                .or_default()
                                .push(v.as_str().unwrap().into());
                        }
                    }
                }
                let inbound = Inbound {
                    method: args["method"].as_str().unwrap().into(),
                    path: path.into(),
                    headers,
                    query: q,
                    body: Bytes::from(
                        args.get("body")
                            .and_then(Value::as_str)
                            .unwrap_or_default()
                            .replace("UPSTREAM", &self.upstream),
                    ),
                    scope: Default::default(),
                };
                let reply = if op == "management" {
                    self.host.serve_management(inbound).await
                } else {
                    self.host.serve_resource(inbound).await
                };
                match reply {
                    None => json!({"handled": false, "status": 0, "headers": {}, "body": ""}),
                    Some(reply) => {
                        let mut headers: BTreeMap<String, Vec<String>> = BTreeMap::new();
                        for (k, v) in reply.headers {
                            headers
                                .entry(cpa_exec::proxy::canonical_header(&k))
                                .or_default()
                                .push(v);
                        }
                        json!({
                            "handled": true,
                            "status": reply.status,
                            "headers": headers,
                            "body": auth::normalize_times(
                                &String::from_utf8_lossy(&reply.body)
                                    .replace(&self.upstream, "UPSTREAM")
                                    .replace(&*self.auth_dir.to_string_lossy(), "AUTHDIR")
                            ),
                        })
                    }
                }
            }
            "unload" => json!(self.host.unload_plugin(args.as_str().unwrap(), None).await),
            "shutdown" => {
                self.host.shutdown_all(None).await;
                Value::Null
            }
            "records" => self.records(),
            "respond" => {
                let dir = self.record_dir.join("respond").join(args["label"].as_str().unwrap());
                std::fs::create_dir_all(&dir).unwrap();
                let path = dir.join(format!("{}.json", args["method"].as_str().unwrap()));
                match args["envelope"].as_str().unwrap() {
                    "" => {
                        let _ = std::fs::remove_file(path);
                    }
                    envelope => std::fs::write(path, envelope).unwrap(),
                }
                Value::Null
            }
            "settle" => {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                Value::Null
            }
            "clear" => {
                for entry in std::fs::read_dir(&self.plugin_dir).unwrap() {
                    std::fs::remove_file(entry.unwrap().path()).unwrap();
                }
                Value::Null
            }
            "call" => calls::call(&self.host, args).await,
            "auth_files" => {
                for (name, content) in args.as_object().unwrap() {
                    std::fs::write(self.auth_dir.join(name), content.as_str().unwrap()).unwrap();
                }
                // The generator also makes a directory with a .json name.
                std::fs::create_dir_all(self.auth_dir.join("dir.json")).unwrap();
                Value::Null
            }
            "auth_manager" => {
                let manager = args.as_array().map(|specs| {
                    Arc::new(auth::GoldenManager::from_specs(specs, &self.auth_dir))
                        as Arc<dyn cpa_plugin::hostauth::AuthManager>
                });
                self.host.set_auth_manager(manager);
                Value::Null
            }
            other => panic!("unknown step {other}"),
        }
    }

    /// Same normalization as the generator: lifecycle config YAML moves to its own
    /// field with directories replaced by placeholders.
    fn records(&self) -> Value {
        let mut out = serde_json::Map::new();
        let mut names: Vec<_> = std::fs::read_dir(&self.record_dir)
            .unwrap()
            .map(|e| e.unwrap().path())
            .filter(|p| !p.is_dir())
            .collect();
        names.sort();
        for path in names {
            let label = path.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&path).unwrap();
            std::fs::remove_file(&path).unwrap();
            let mut entries = Vec::new();
            for line in text.lines() {
                let mut entry: serde_json::Map<String, Value> = serde_json::from_str(line).unwrap();
                let request = entry["request"]
                    .as_str()
                    .unwrap()
                    .replace(&*self.record_dir.to_string_lossy(), "RECORDDIR")
                    .replace(&self.upstream, "UPSTREAM");
                // A management body carrying the upstream address is base64 in the record.
                let request = match serde_json::from_str::<Value>(&request)
                    .ok()
                    .and_then(|v| v.get("Body").and_then(Value::as_str).map(str::to_owned))
                {
                    Some(b64) => {
                        use base64::Engine as _;
                        let engine = base64::engine::general_purpose::STANDARD;
                        match engine.decode(&b64) {
                            Ok(body) if String::from_utf8_lossy(&body).contains(&self.upstream) => {
                                let normalized = String::from_utf8_lossy(&body).replace(&self.upstream, "UPSTREAM");
                                request.replacen(&b64, &engine.encode(normalized), 1)
                            }
                            _ => request,
                        }
                    }
                    None => request,
                };
                entry.insert("request".into(), request.clone().into());
                if let Ok(Value::Object(req)) = serde_json::from_str::<Value>(&request)
                    && let Some(raw) = req.get("config_yaml")
                {
                    use base64::Engine as _;
                    let yaml = base64::engine::general_purpose::STANDARD
                        .decode(raw.as_str().unwrap())
                        .unwrap();
                    let yaml = String::from_utf8(yaml).unwrap();
                    entry.insert(
                        "config_yaml".into(),
                        yaml.replace(&*self.record_dir.to_string_lossy(), "RECORDDIR")
                            .replace(&*self.plugin_dir.to_string_lossy(), "PLUGINDIR")
                            .replace(&*self.auth_dir.to_string_lossy(), "AUTHDIR")
                            .into(),
                    );
                    let encoded = serde_json::to_string(raw).unwrap();
                    entry.insert(
                        "request".into(),
                        request.replacen(&encoded, "\"<config_yaml>\"", 1).into(),
                    );
                }
                entries.push(Value::Object(entry));
            }
            out.insert(label, Value::Array(entries));
        }
        Value::Object(out)
    }
}

/// Callback context IDs are opaque counters; contexts opened from background tasks
/// (request completion) are numbered in scheduling order, so only their presence counts.
fn without_callback_ids(s: &str) -> String {
    const KEY: &str = "\"host_callback_id\":\"";
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(at) = rest.find(KEY) {
        out.push_str(&rest[..at + KEY.len()]);
        rest = rest[at + KEY.len()..].trim_start_matches(|c: char| c.is_ascii_digit());
        out.push('#');
    }
    out.push_str(rest);
    out
}

/// The first differing leaf, for failure messages.
fn first_diff(go: &Value, rust: &Value, path: &str) -> String {
    match (go, rust) {
        (Value::Object(a), Value::Object(b)) => {
            for (k, v) in a {
                match b.get(k) {
                    Some(w) if !same(v, w) => return first_diff(v, w, &format!("{path}.{k}")),
                    None => return format!("{path}.{k}: missing in rust"),
                    _ => {}
                }
            }
            match b.keys().find(|k| !a.contains_key(*k)) {
                Some(k) => format!("{path}.{k}: only in rust"),
                None => format!("{path}: ?"),
            }
        }
        (Value::Array(a), Value::Array(b)) if a.len() == b.len() => {
            let i = a.iter().zip(b).position(|(v, w)| !same(v, w)).unwrap_or(0);
            first_diff(&a[i], &b[i], &format!("{path}[{i}]"))
        }
        // Long strings: the neighbourhood of the first differing character.
        (Value::String(a), Value::String(b)) if a.len() > 300 || b.len() > 300 => {
            let at = a
                .bytes()
                .zip(b.bytes())
                .position(|(x, y)| x != y)
                .unwrap_or(a.len().min(b.len()));
            let window = |s: &str| {
                let mut start = at.saturating_sub(120).min(s.len());
                while !s.is_char_boundary(start) {
                    start -= 1;
                }
                let mut end = (at + 120).min(s.len());
                while !s.is_char_boundary(end) {
                    end += 1;
                }
                format!("…{:?}…", &s[start..end])
            };
            format!("{path} (byte {at}):\n    go:   {}\n    rust: {}", window(a), window(b))
        }
        _ => format!("{path}:\n    go:   {go}\n    rust: {rust}"),
    }
}

/// Config YAML is compared as YAML; everything else exactly.
fn same(go: &Value, rust: &Value) -> bool {
    match (go, rust) {
        (Value::Object(a), Value::Object(b)) => {
            a.len() == b.len()
                && a.iter().all(|(k, v)| {
                    b.get(k).is_some_and(|w| {
                        if k == "config_yaml" {
                            let parse = |v: &Value| {
                                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(v.as_str().unwrap_or_default()).ok()
                            };
                            parse(v) == parse(w)
                        } else {
                            same(v, w)
                        }
                    })
                })
        }
        (Value::Array(a), Value::Array(b)) => a.len() == b.len() && a.iter().zip(b).all(|(v, w)| same(v, w)),
        (Value::String(a), Value::String(b)) => without_callback_ids(a) == without_callback_ids(b),
        _ => go == rust,
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn rust_host_matches_go_host() {
    let Some(built) = support::built_plugins_for("go_host::rust_host_matches_go_host") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/pluginhost_go.json")).unwrap();
    let scratch = support::scratch("go-host");
    let runner = Runner {
        built: built.to_path_buf(),
        plugin_dir: scratch.join("plugins"),
        record_dir: scratch.join("records"),
        auth_dir: scratch.join("auths"),
        upstream: cpa_plugin::testing::raw_upstream().await,
        host: Host::new(),
    };
    std::fs::create_dir_all(&runner.plugin_dir).unwrap();
    std::fs::create_dir_all(&runner.record_dir).unwrap();
    std::fs::create_dir_all(&runner.auth_dir).unwrap();
    let mut failures = Vec::new();
    for (i, step) in fixture["steps"].as_array().unwrap().iter().enumerate() {
        let op = step["op"].as_str().unwrap();
        let got = runner.step(op, &step["args"]).await;
        if !same(&step["result"], &got) {
            failures.push(format!(
                "step {i} {op} {}\n  {}",
                step["args"].to_string().chars().take(160).collect::<String>(),
                first_diff(&step["result"], &got, "")
            ));
        }
    }
    let _ = std::fs::remove_dir_all(Path::new(&scratch));
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
