//! Replays `fixtures/pluginhost_go.json` (generated by `reference/pluginhost` from the Go
//! plugin host at 6fecc6e) against the Rust host with the same c-shared plugins and
//! compares every observable: registered plugins and their order, load state, the
//! management and resource route tables and responses, host callback answers, and the
//! exact request bytes every plugin received (config YAML compared as YAML, since the
//! emitters format differently).

mod support;

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use bytes::Bytes;
use cpa_plugin::Host;
use cpa_plugin::gojson::Header;
use cpa_plugin::management::Inbound;
use serde_json::{Value, json};

struct Runner {
    built: PathBuf,
    plugin_dir: PathBuf,
    record_dir: PathBuf,
    host: Host,
}

impl Runner {
    fn placeholders(&self, text: &str) -> String {
        text.replace("PLUGINDIR", &self.plugin_dir.to_string_lossy())
            .replace("RECORDDIR", &self.record_dir.to_string_lossy())
    }

    fn registered(&self) -> Value {
        Value::Array(
            self.host
                .registered_plugins()
                .into_iter()
                .map(|info| {
                    let metadata: Value = serde_json::from_slice(&cpa_plugin::gojson::to_vec(&info.metadata)).unwrap();
                    json!({
                        "id": info.id,
                        "priority": info.priority,
                        "metadata": metadata,
                        "supports_oauth": info.supports_oauth,
                        "oauth_provider": info.oauth_provider,
                        "supports_quota": info.supports_quota,
                        "quota_provider": info.quota_provider,
                        "menus": info.menus.iter().map(|m| json!({"path": m.path, "menu": m.menu, "description": m.description})).collect::<Vec<_>>(),
                    })
                })
                .collect(),
        )
    }

    async fn step(&self, op: &str, args: &Value) -> Value {
        match op {
            "files" => {
                for (name, from) in args.as_object().unwrap() {
                    let from = self.built.join(format!("{}.so", from.as_str().unwrap()));
                    std::fs::copy(from, self.plugin_dir.join(name)).unwrap();
                }
                Value::Null
            }
            "apply" => {
                let cfg = cpa_core::config::Config::parse(&self.placeholders(args.as_str().unwrap())).unwrap();
                self.host.apply_config(Arc::new(cfg)).await;
                self.registered()
            }
            "loaded" => {
                let mut out = serde_json::Map::new();
                for id in args.as_array().unwrap() {
                    let id = id.as_str().unwrap();
                    out.insert(
                        id.into(),
                        json!([self.host.plugin_loaded(id), self.host.plugin_registered(id)]),
                    );
                }
                Value::Object(out)
            }
            "register_management" => {
                let reserved: HashSet<String> = args
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_owned())
                    .collect();
                self.host.register_management_routes(&reserved).await;
                self.registered()
            }
            "management" | "resource" => {
                let target = args["target"].as_str().unwrap();
                let (path, query) = target.split_once('?').unwrap_or((target, ""));
                let mut q = Header::new();
                for (k, v) in url::form_urlencoded::parse(query.as_bytes()) {
                    q.entry(k.into_owned()).or_default().push(v.into_owned());
                }
                let mut headers = Header::new();
                if let Some(h) = args.get("headers").and_then(Value::as_object) {
                    for (k, vs) in h {
                        for v in vs.as_array().unwrap() {
                            headers
                                .entry(cpa_exec::proxy::canonical_header(k))
                                .or_default()
                                .push(v.as_str().unwrap().into());
                        }
                    }
                }
                let inbound = Inbound {
                    method: args["method"].as_str().unwrap().into(),
                    path: path.into(),
                    headers,
                    query: q,
                    body: Bytes::from(args.get("body").and_then(Value::as_str).unwrap_or_default().to_owned()),
                    scope: Default::default(),
                };
                let reply = if op == "management" {
                    self.host.serve_management(inbound).await
                } else {
                    self.host.serve_resource(inbound).await
                };
                match reply {
                    None => json!({"handled": false, "status": 0, "headers": {}, "body": ""}),
                    Some(reply) => {
                        let mut headers: BTreeMap<String, Vec<String>> = BTreeMap::new();
                        for (k, v) in reply.headers {
                            headers
                                .entry(cpa_exec::proxy::canonical_header(&k))
                                .or_default()
                                .push(v);
                        }
                        json!({
                            "handled": true,
                            "status": reply.status,
                            "headers": headers,
                            "body": String::from_utf8_lossy(&reply.body),
                        })
                    }
                }
            }
            "unload" => json!(self.host.unload_plugin(args.as_str().unwrap(), None).await),
            "shutdown" => {
                self.host.shutdown_all(None).await;
                Value::Null
            }
            "records" => self.records(),
            other => panic!("unknown step {other}"),
        }
    }

    /// Same normalization as the generator: lifecycle config YAML moves to its own
    /// field with directories replaced by placeholders.
    fn records(&self) -> Value {
        let mut out = serde_json::Map::new();
        let mut names: Vec<_> = std::fs::read_dir(&self.record_dir)
            .unwrap()
            .map(|e| e.unwrap().path())
            .collect();
        names.sort();
        for path in names {
            let label = path.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&path).unwrap();
            std::fs::remove_file(&path).unwrap();
            let mut entries = Vec::new();
            for line in text.lines() {
                let mut entry: serde_json::Map<String, Value> = serde_json::from_str(line).unwrap();
                let request = entry["request"].as_str().unwrap().to_owned();
                if let Ok(Value::Object(req)) = serde_json::from_str::<Value>(&request)
                    && let Some(raw) = req.get("config_yaml")
                {
                    use base64::Engine as _;
                    let yaml = base64::engine::general_purpose::STANDARD
                        .decode(raw.as_str().unwrap())
                        .unwrap();
                    let yaml = String::from_utf8(yaml).unwrap();
                    entry.insert(
                        "config_yaml".into(),
                        yaml.replace(&*self.record_dir.to_string_lossy(), "RECORDDIR")
                            .replace(&*self.plugin_dir.to_string_lossy(), "PLUGINDIR")
                            .into(),
                    );
                    let encoded = serde_json::to_string(raw).unwrap();
                    entry.insert(
                        "request".into(),
                        request.replacen(&encoded, "\"<config_yaml>\"", 1).into(),
                    );
                }
                entries.push(Value::Object(entry));
            }
            out.insert(label, Value::Array(entries));
        }
        Value::Object(out)
    }
}

/// Config YAML is compared as YAML; everything else exactly.
fn same(go: &Value, rust: &Value) -> bool {
    match (go, rust) {
        (Value::Object(a), Value::Object(b)) => {
            a.len() == b.len()
                && a.iter().all(|(k, v)| {
                    b.get(k).is_some_and(|w| {
                        if k == "config_yaml" {
                            let parse = |v: &Value| {
                                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(v.as_str().unwrap_or_default()).ok()
                            };
                            parse(v) == parse(w)
                        } else {
                            same(v, w)
                        }
                    })
                })
        }
        (Value::Array(a), Value::Array(b)) => a.len() == b.len() && a.iter().zip(b).all(|(v, w)| same(v, w)),
        _ => go == rust,
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn rust_host_matches_go_host() {
    let Some(built) = support::built_plugins() else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/pluginhost_go.json")).unwrap();
    let scratch = support::scratch("go-host");
    let runner = Runner {
        built: built.to_path_buf(),
        plugin_dir: scratch.join("plugins"),
        record_dir: scratch.join("records"),
        host: Host::new(),
    };
    std::fs::create_dir_all(&runner.plugin_dir).unwrap();
    std::fs::create_dir_all(&runner.record_dir).unwrap();
    let mut failures = Vec::new();
    for (i, step) in fixture["steps"].as_array().unwrap().iter().enumerate() {
        let op = step["op"].as_str().unwrap();
        let got = runner.step(op, &step["args"]).await;
        if !same(&step["result"], &got) {
            failures.push(format!(
                "step {i} {op} {}\n  go:   {}\n  rust: {}",
                step["args"].to_string().chars().take(160).collect::<String>(),
                step["result"],
                got
            ));
        }
    }
    let _ = std::fs::remove_dir_all(Path::new(&scratch));
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
