//! Replays `fixtures/pluginstore_go.json` (generated by `reference/pluginstore` from the
//! Go plugin store at 6fecc6e) against `cpa_plugin::store`: registry, manifest,
//! version, checksum and auth rules, the client's requests (URL and headers of every
//! request, through a fake doer) and results, and installs of real zip archives
//! (results and the exact files written, with their permissions).

// The file listing compares Unix permission bits.
#![cfg(unix)]

mod support;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::SystemTime;

use base64::Engine as _;
use bytes::Bytes;
use cpa_plugin::gojson::{self, GoJson};
use cpa_plugin::store::{
    self, AuthConfig, Client, Doer, DoerResponse, GitHubRateLimiter, Headers, InstallOptions, InstallResult, Manifest,
    Plugin, PluginSyncResponse, Release, Source, StoreError,
};
use futures_util::StreamExt;
use futures_util::future::BoxFuture;
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

/// The fake `httpfetch.Doer` of the generator: fixed routes by exact URL, every
/// request recorded.
struct FakeDoer {
    routes: serde_json::Map<String, Value>,
    requests: Mutex<Vec<Value>>,
}

impl Doer for FakeDoer {
    fn get(&self, url: &str, headers: &Headers) -> BoxFuture<'_, Result<DoerResponse, String>> {
        self.requests
            .lock()
            .unwrap()
            .push(json!({"url": url, "headers": headers}));
        let route = self.routes.get(url).cloned();
        let url = url.to_owned();
        Box::pin(async move {
            let Some(route) = route else {
                return Err(format!("no route for {url}"));
            };
            if let Some(e) = route["error"].as_str().filter(|e| !e.is_empty()) {
                return Err(e.to_owned());
            }
            let body = match route["body_b64"].as_str().filter(|b| !b.is_empty()) {
                Some(b64) => base64::engine::general_purpose::STANDARD.decode(b64).unwrap(),
                None => route["body"].as_str().unwrap_or_default().as_bytes().to_vec(),
            };
            let headers: Headers = serde_json::from_value(route["headers"].clone()).unwrap_or_default();
            Ok(DoerResponse {
                status: route["status"].as_u64().unwrap() as u16,
                headers,
                body: futures_util::stream::once(async move { Ok(Bytes::from(body)) }).boxed(),
            })
        })
    }
}

fn go<T: GoJson>(v: &Value) -> T {
    gojson::from_slice(&serde_json::to_vec(v).unwrap()).unwrap_or_else(|e| panic!("decode {v}: {e}"))
}

fn to_value<T: GoJson>(v: &T) -> Value {
    serde_json::from_slice(&gojson::to_vec(v)).unwrap()
}

fn str_of(v: &Value, key: &str) -> String {
    v[key].as_str().unwrap_or_default().to_owned()
}

fn strings(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| a.iter().map(|s| s.as_str().unwrap().to_owned()).collect())
        .unwrap_or_default()
}

fn source(v: &Value) -> Source {
    Source {
        id: str_of(v, "id"),
        name: str_of(v, "name"),
        url: str_of(v, "url"),
    }
}

fn source_value(s: &Source) -> Value {
    json!({"id": s.id, "name": s.name, "url": s.url})
}

/// Go `AuthConfig` from its JSON tags.
fn auth_config(v: &Value) -> AuthConfig {
    AuthConfig {
        matches: str_of(v, "match"),
        apply_to: strings(&v["apply_to"]),
        auth_type: str_of(v, "type"),
        token_env: str_of(v, "token_env"),
        username_env: str_of(v, "username_env"),
        password_env: str_of(v, "password_env"),
        header_name: str_of(v, "header_name"),
        header_value_env: str_of(v, "header_value_env"),
        allow_insecure: v["allow_insecure"].as_bool().unwrap_or(false),
    }
}

fn auth_configs(v: &Value) -> Vec<AuthConfig> {
    v.as_array()
        .map(|a| a.iter().map(auth_config).collect())
        .unwrap_or_default()
}

/// The generator's `outcome`: `{"ok": value}` or `{"error", "rate_limited"}`, with
/// cooldowns ending within the hour written as `SOON(<seconds>)`.
fn outcome(r: Result<Value, StoreError>) -> Value {
    match r {
        Ok(v) => json!({"ok": v}),
        Err(e) => {
            let mut text = e.to_string();
            if let Some(rate) = e.rate_limit() {
                let now = SystemTime::now();
                let soon = rate
                    .retry_at
                    .duration_since(now)
                    .map_or(true, |d| d < std::time::Duration::from_secs(3600));
                if soon {
                    let stamp = chrono::DateTime::<chrono::Utc>::from(rate.retry_at)
                        .format("%Y-%m-%dT%H:%M:%SZ")
                        .to_string();
                    text = text.replace(&stamp, &format!("SOON({})", rate.retry_after_seconds(now)));
                }
            }
            json!({"error": text, "rate_limited": e.rate_limit().is_some()})
        }
    }
}

fn plain<T>(r: Result<T, String>, f: impl FnOnce(T) -> Value) -> Value {
    outcome(r.map(f).map_err(StoreError::Other))
}

fn client(args: &Value) -> (Client, Arc<FakeDoer>) {
    let doer = Arc::new(FakeDoer {
        routes: args["routes"].as_object().cloned().unwrap_or_default(),
        requests: Mutex::new(Vec::new()),
    });
    let mut client = Client::new(doer.clone());
    client.network_scope = str_of(args, "network_scope");
    client.rate_limiter = Some(Arc::new(GitHubRateLimiter::default()));
    client.registry_url = str_of(args, "registry_url");
    client.user_agent = str_of(args, "user_agent");
    client.auth = auth_configs(&args["auth"]);
    (client, doer)
}

fn install_result(r: &InstallResult, root: &Path) -> Value {
    let mut v = serde_json::Map::new();
    v.insert("id".into(), json!(r.id));
    v.insert("version".into(), json!(r.version));
    if !r.release_tag.is_empty() {
        v.insert("release_tag".into(), json!(r.release_tag));
    }
    if !r.install_type.is_empty() {
        v.insert("install_type".into(), json!(r.install_type));
    }
    v.insert(
        "path".into(),
        json!(r.path.replace(&*root.to_string_lossy(), "PLUGINS")),
    );
    v.insert("overwritten".into(), json!(r.overwritten));
    v.insert("skipped".into(), json!(r.skipped));
    Value::Object(v)
}

/// Every file under `root`: relative path, SHA-256 and permission bits in octal.
fn list_files(root: &Path) -> Value {
    fn walk(dir: &Path, root: &Path, out: &mut Vec<(String, Value)>) {
        let Ok(entries) = std::fs::read_dir(dir) else { return };
        for entry in entries {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(&path, root, out);
                continue;
            }
            use std::os::unix::fs::PermissionsExt as _;
            let data = std::fs::read(&path).unwrap();
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            let rel = path.strip_prefix(root).unwrap().to_string_lossy().into_owned();
            let sum: String = Sha256::digest(&data).iter().map(|b| format!("{b:02x}")).collect();
            out.push((
                rel.clone(),
                json!({"path": rel, "sha256": sum, "mode": format!("{mode:o}")}),
            ));
        }
    }
    let mut out = Vec::new();
    walk(root, root, &mut out);
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Value::Array(out.into_iter().map(|(_, v)| v).collect())
}

struct Installs {
    dir: Option<PathBuf>,
    count: usize,
}

impl Installs {
    async fn run(&mut self, args: &Value) -> Value {
        if self.dir.is_none() || args["fresh"].as_bool().unwrap_or(false) {
            self.count += 1;
            self.dir = Some(support::scratch(&format!("store-go-{}", self.count)));
        }
        let dir = self.dir.clone().unwrap();
        let (client, doer) = client(&args["client"]);
        let options = InstallOptions {
            plugins_dir: dir.to_string_lossy().into_owned(),
            goos: str_of(args, "goos"),
            goarch: str_of(args, "goarch"),
            ..Default::default()
        };
        let env = args["client"]["env"].clone();
        let result = match args["call"].as_str().unwrap() {
            "install" => {
                let plugin: Plugin = go(&args["plugin"]);
                set_env_and(&env, client.install(plugin, options)).await
            }
            "install_version" => {
                let plugin: Plugin = go(&args["plugin"]);
                let (tag, version) = (str_of(args, "tag"), str_of(args, "version"));
                set_env_and(&env, client.install_version(plugin, &tag, &version, options)).await
            }
            "install_manifest" => {
                let manifest: Manifest = go(&args["manifest"]);
                set_env_and(&env, client.install_manifest(&manifest, options)).await
            }
            "install_archive" => {
                let plugin: Plugin = go(&args["plugin"]);
                let data = base64::engine::general_purpose::STANDARD
                    .decode(str_of(args, "zip"))
                    .unwrap();
                store::install_archive(&data, &plugin, options)
            }
            call => panic!("unknown install call {call}"),
        };
        let root = dir.to_string_lossy().into_owned();
        let result = match result {
            Ok(r) => Ok(install_result(&r, &dir)),
            Err(StoreError::Other(e)) => Err(StoreError::Other(e.replace(&root, "PLUGINS"))),
            Err(e) => Err(e),
        };
        // The generator's map[string]any: keys in sorted order.
        json!({
            "files": list_files(&dir),
            "requests": *doer.requests.lock().unwrap(),
            "result": outcome(result),
        })
    }
}

/// Awaits `fut` with the case's environment set (the generator's `withEnv` around
/// the call).
async fn set_env_and<F: std::future::Future>(env: &Value, fut: F) -> F::Output {
    let vars: Vec<String> = env.as_object().map(|m| m.keys().cloned().collect()).unwrap_or_default();
    if let Some(m) = env.as_object() {
        for (k, v) in m {
            // SAFETY: this binary has a single test, run on a current-thread runtime,
            // so nothing reads the environment concurrently.
            unsafe { std::env::set_var(k, v.as_str().unwrap()) };
        }
    }
    let out = fut.await;
    for k in vars {
        // SAFETY: as above.
        unsafe { std::env::remove_var(k) };
    }
    out
}

async fn run_client(args: &Value) -> Value {
    let (client, doer) = client(&args["client"]);
    let client = &client;
    let mut results = Vec::new();
    let env = args["client"]["env"].clone();
    for call in args["calls"].as_array().unwrap() {
        let plugin = || -> Plugin { go(&call["plugin"]) };
        let fut: BoxFuture<'_, Result<Value, StoreError>> = match call["call"].as_str().unwrap() {
            "fetch_registry" => Box::pin(async { client.fetch_registry().await.map(|r| to_value(&r)) }),
            "fetch_latest_release" => {
                let p = plugin();
                Box::pin(async move { client.fetch_latest_release(&p).await.map(|r| to_value(&r)) })
            }
            "fetch_release_by_tag" => {
                let (p, tag) = (plugin(), str_of(call, "tag"));
                Box::pin(async move { client.fetch_release_by_tag(&p, &tag).await.map(|r| to_value(&r)) })
            }
            "download_asset" => {
                let asset: store::ReleaseAsset = go(&call["asset"]);
                Box::pin(async move {
                    client
                        .download_asset(&asset)
                        .await
                        .map(|b| json!(String::from_utf8_lossy(&b)))
                })
            }
            "download_artifact" => {
                let artifact: store::Artifact = go(&call["artifact"]);
                Box::pin(async move {
                    client
                        .download_artifact(&artifact)
                        .await
                        .map(|b| json!(String::from_utf8_lossy(&b)))
                })
            }
            "latest_release_cache_key" => {
                let p = plugin();
                Box::pin(async move { client.latest_release_cache_key(&p).map(|k| json!(k)) })
            }
            other => panic!("unknown client call {other}"),
        };
        results.push(outcome(set_env_and(&env, fut).await));
    }
    json!({"requests": *doer.requests.lock().unwrap(), "results": results})
}

async fn replay(op: &str, args: &Value, installs: &mut Installs) -> Value {
    match op {
        "parse_registry" => plain(store::parse_registry(str_of(args, "data").as_bytes()), |r| to_value(&r)),
        "normalize_sources" => plain(store::normalize_sources(&strings(&args["urls"])), |s| {
            Value::Array(s.iter().map(source_value).collect())
        }),
        "manifest_from_plugin" => plain(
            store::manifest_from_plugin(&source(&args["source"]), &go(&args["plugin"])),
            |m| to_value(&m),
        ),
        "manifest_from_release" => {
            let release = Release {
                tag_name: str_of(args, "tag"),
                ..Default::default()
            };
            plain(
                store::manifest_from_release(&source(&args["source"]), &go(&args["plugin"]), &release),
                |m| to_value(&m),
            )
        }
        "manifest_validate" => plain(go::<Manifest>(&args["manifest"]).validate(), |()| Value::Null),
        "manifest_yaml" => {
            let node: serde_yaml_ng::Value = serde_yaml_ng::from_str(&str_of(args, "text")).unwrap();
            let decoded = Manifest::from_yaml(&node);
            let m = decoded.clone().unwrap_or_default();
            let (id, url) = if decoded.is_some() {
                (m.source_id.trim().to_owned(), m.source_url.trim().to_owned())
            } else {
                (String::new(), String::new())
            };
            json!({"ok": decoded.is_some(), "source_id": id, "source_url": url})
        }
        "update_available" => json!(store::update_available(
            &str_of(args, "installed"),
            &str_of(args, "latest")
        )),
        "parse_checksums" => plain(store::parse_checksums(str_of(args, "data").as_bytes()), |sums| {
            json!(sums)
        }),
        "verify_checksum" => {
            let sums: BTreeMap<String, String> = serde_json::from_value(args["checksums"].clone()).unwrap();
            plain(
                store::verify_checksum(&str_of(args, "name"), str_of(args, "data").as_bytes(), &sums),
                |()| Value::Null,
            )
        }
        "plugin_auth_configured" => {
            let (source, plugin, auth) = (
                source(&args["source"]),
                go(&args["plugin"]),
                auth_configs(&args["auth"]),
            );
            set_env_and(&args["env"], async {
                json!(store::plugin_auth_configured(&source, &plugin, &auth))
            })
            .await
        }
        "client" => run_client(args).await,
        "install" => installs.run(args).await,
        "home_sync_validate" => {
            let response: PluginSyncResponse = gojson::from_slice(str_of(args, "body").as_bytes()).unwrap();
            let now = chrono::DateTime::parse_from_rfc3339(&str_of(args, "now")).unwrap();
            plain(response.validate(now), |()| Value::Null)
        }
        other => panic!("unknown op {other}"),
    }
}

#[test]
fn store_matches_go() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/pluginstore_go.json")).expect("pluginstore_go.json parses");
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let mut installs = Installs { dir: None, count: 0 };
    let mut failures = Vec::new();
    for (index, case) in fixture["cases"].as_array().unwrap().iter().enumerate() {
        let op = case["op"].as_str().unwrap();
        let got = runtime.block_on(replay(op, &case["args"], &mut installs));
        // Compared as serialized text so field order counts too.
        let (want, got) = (case["result"].to_string(), got.to_string());
        if want != got {
            let args = case["args"].to_string();
            let args = &args[..args.len().min(600)];
            failures.push(format!("case {index} ({op}) args {args}\n  want {want}\n  got  {got}"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        fixture["cases"].as_array().unwrap().len(),
        failures.join("\n")
    );
}
