//! The xAI upstream WebSocket against goldens from the pinned Go `XAIAutoExecutor`
//! (`tests/fixtures/xai_ws_go.json`, generated by `tests/reference/xai_ws`): each
//! scenario's turns run in order on one downstream session against a scripted loopback
//! upstream (axum WebSocket for `/v1/responses`, HTTP for `/v1/responses/compact`), and
//! every turn's downstream chunks, error, upstream frames, compaction requests and
//! handshake headers are compared.

use super::*;
use std::sync::Mutex as StdMutex;

use axum::extract::ws::{CloseFrame, Message as AxMessage, WebSocket as AxSocket, WebSocketUpgrade};
use axum::extract::{FromRequestParts, State};
use axum::response::{IntoResponse, Response};
use cpa_core::exec::{Caller, Operation};
use serde_json::Value;

const FIXTURE: &str = include_str!("../tests/fixtures/xai_ws_go.json");

/// The handshake headers compared with Go. Go's dialer also sends `User-Agent:
/// Go-http-client/1.1` and offers `permessage-deflate`; those belong to the shared dialer.
const COMPARED_HEADERS: [&str; 4] = ["Authorization", "Content-Type", "X-Grok-Conv-Id", "X-Trace"];

/// Turns whose Go error text is gorilla's close message, which the shared reader does
/// not keep (see `pool_error`): only status and retry hint are compared.
const GORILLA_CLOSE_TEXT: [&str; 1] = ["upstream_closes_mid_turn"];

#[derive(Default)]
struct Recorded {
    upgrades: Vec<String>,
    frames: Vec<String>,
    http: Vec<String>,
}

#[derive(Default)]
struct Script {
    turn: Option<Value>,
    recorded: Recorded,
}

type Shared = Arc<StdMutex<Script>>;

fn canonical(name: &str) -> String {
    name.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + &chars.as_str().to_ascii_lowercase(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("-")
}

async fn handler(State(shared): State<Shared>, req: axum::extract::Request) -> Response {
    let (mut parts, body) = req.into_parts();
    let uri = parts
        .uri
        .path_and_query()
        .map(|p| p.as_str().to_owned())
        .unwrap_or_default();
    if parts.headers.contains_key("upgrade") {
        let mut lines: Vec<String> = COMPARED_HEADERS
            .iter()
            .filter_map(|name| {
                parts
                    .headers
                    .get(name.to_ascii_lowercase())
                    .map(|v| format!("{}: {}", canonical(name), v.to_str().unwrap()))
            })
            .collect();
        lines.sort();
        let reject = {
            let mut script = shared.lock().unwrap();
            script.recorded.upgrades.push(format!("{uri}\n{}", lines.join("\n")));
            script
                .turn
                .as_ref()
                .and_then(|t| t.get("reject"))
                .filter(|r| !r.is_null())
                .cloned()
        };
        if let Some(reject) = reject {
            let status = http::StatusCode::from_u16(reject["status"].as_u64().unwrap() as u16).unwrap();
            return (
                status,
                [("content-type", "application/json")],
                reject["body"].as_str().unwrap().to_owned(),
            )
                .into_response();
        }
        let upgrade = WebSocketUpgrade::from_request_parts(&mut parts, &()).await.unwrap();
        return upgrade.on_upgrade(move |socket| serve_socket(socket, shared));
    }
    let body = axum::body::to_bytes(body, usize::MAX).await.unwrap();
    let compact = {
        let mut script = shared.lock().unwrap();
        script
            .recorded
            .http
            .push(format!("{} {uri}\n{}", parts.method, String::from_utf8_lossy(&body)));
        script
            .turn
            .as_ref()
            .and_then(|t| t.get("compact"))
            .filter(|r| !r.is_null())
            .cloned()
    };
    match compact {
        Some(reply) => (
            http::StatusCode::from_u16(reply["status"].as_u64().unwrap() as u16).unwrap(),
            [("content-type", "application/json")],
            reply["body"].as_str().unwrap().to_owned(),
        )
            .into_response(),
        None => http::StatusCode::from_u16(599).unwrap().into_response(),
    }
}

async fn serve_socket(mut socket: AxSocket, shared: Shared) {
    while let Some(Ok(message)) = socket.recv().await {
        let AxMessage::Text(text) = message else { continue };
        let act = {
            let mut script = shared.lock().unwrap();
            script.recorded.frames.push(text.as_str().to_owned());
            let n = script.recorded.frames.len();
            script
                .turn
                .as_ref()
                .and_then(|t| t["acts"].as_array())
                .and_then(|acts| acts.get(n - 1))
                .cloned()
        };
        let Some(act) = act else { continue };
        for frame in act["send"].as_array().into_iter().flatten() {
            if socket.send(AxMessage::text(frame.as_str().unwrap())).await.is_err() {
                return;
            }
        }
        if act["binary"].as_bool().unwrap_or(false) {
            let _ = socket.send(AxMessage::Binary(vec![1u8, 2, 3].into())).await;
        }
        if let Some(code) = act["close"].as_u64().filter(|c| *c != 0) {
            let _ = socket
                .send(AxMessage::Close(Some(CloseFrame {
                    code: code as u16,
                    reason: act["close_text"].as_str().unwrap_or_default().into(),
                })))
                .await;
            return;
        }
    }
}

fn credential(id: &str, attrs: &Value, addr: &str) -> Credential {
    let mut metadata = serde_json::Map::new();
    metadata.insert("type".into(), "xai".into());
    let mut c = Credential::from_file(
        std::path::Path::new("/fixture"),
        std::path::Path::new("/fixture/xai.json"),
        metadata,
    )
    .unwrap();
    c.id = id.to_owned();
    for (k, v) in attrs.as_object().unwrap() {
        c.attributes
            .insert(k.clone(), v.as_str().unwrap().replace("UPSTREAM", addr));
    }
    c
}

fn request(turn: &Value, session: &str) -> ExecRequest {
    let payload = Bytes::from(turn["payload"].as_str().unwrap().to_owned());
    let headers = HeaderMap::new();
    // Go's executor-side session fallback (EnsureSessionContext -> CanonicalSessionID).
    let meta = cpa_common::session::Meta {
        execution_session: Some(session),
        derived: None,
    };
    let id = cpa_common::session::extract_session_id(&headers, &payload, &meta);
    let model = turn["model"].as_str().unwrap_or("grok-4.3").to_owned();
    ExecRequest {
        operation: Operation::Generate,
        source_format: Format::OpenAIResponse,
        response_format: Format::OpenAIResponse,
        requested_model: model.clone(),
        model,
        original_body: payload.clone(),
        body: payload,
        stream: true,
        alt: None,
        session: Some(id)
            .filter(|id| !id.is_empty())
            .map(|id| cpa_common::session::bound_session_identity(&id)),
        execution_session: Some(session.to_owned()),
        derived_session: None,
        resolved_model: None,
        usage: Default::default(),
        request_path: "/v1/responses".into(),
        headers,
        caller: Caller {
            principal: String::new(),
            source: "authorization",
        },
    }
}

fn error_json(e: &ExecError) -> Value {
    serde_json::json!({
        "status": e.status,
        "message": String::from_utf8_lossy(&e.body),
        "retry_after_ms": e.retry_after.map_or(0, |d| d.as_millis() as i64),
    })
}

#[tokio::test]
async fn turns_match_go() {
    let scenarios: Vec<Value> = serde_json::from_str(FIXTURE).unwrap();
    assert_eq!(scenarios.len(), 18);
    let mut failures = Vec::new();
    for s in &scenarios {
        let name = s["name"].as_str().unwrap();
        let shared: Shared = Arc::default();
        let app = axum::Router::new().fallback(handler).with_state(shared.clone());
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let server = tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
        let executor = XaiExecutor::with_client(wreq::Client::new());
        let cfg = Config::default();
        let session = s["session"].as_str().unwrap();
        let credentials: HashMap<String, Credential> = s["auths"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(id, attrs)| (id.clone(), credential(id, attrs, &addr)))
            .collect();
        let normalize = |text: &str| text.replace(&addr, "UPSTREAM");
        for (i, turn) in s["turns"].as_array().unwrap().iter().enumerate() {
            {
                let mut script = shared.lock().unwrap();
                script.turn = Some(turn.clone());
                script.recorded = Recorded::default();
            }
            let mut chunks: Vec<String> = Vec::new();
            let mut error = Value::Null;
            if turn["close"].as_bool().unwrap_or(false) {
                executor.close_session(session);
            } else {
                let credential = &credentials[turn["auth"].as_str().unwrap()];
                let exec_session = ExecSession {
                    id: session.to_owned(),
                    continuation: turn["continuation"].as_bool().unwrap_or(false),
                };
                match executor
                    .execute_in_session(credential, request(turn, session), &cfg, &exec_session)
                    .await
                {
                    Err(e) => error = error_json(&e),
                    Ok(response) => {
                        let ResponseBody::Stream(mut stream) = response.body else {
                            panic!("{name}: buffered response");
                        };
                        while let Some(item) = stream.next().await {
                            match item {
                                Ok(chunk) => chunks.push(normalize(&String::from_utf8_lossy(&chunk))),
                                Err(e) => error = error_json(&e),
                            }
                        }
                    }
                }
            }
            tokio::time::sleep(Duration::from_millis(50)).await;
            let recorded = std::mem::take(&mut shared.lock().unwrap().recorded);
            let mut diffs = Vec::new();
            let want_chunks: Vec<String> = turn["chunks"]
                .as_array()
                .unwrap()
                .iter()
                .map(|c| c.as_str().unwrap().to_owned())
                .collect();
            if chunks != want_chunks {
                diffs.push(format!("chunks:\n  go   {want_chunks:#?}\n  rust {chunks:#?}"));
            }
            let mut want_error = turn["error"].clone();
            if let Some(message) = want_error.get_mut("message") {
                *message = Value::String(normalize(message.as_str().unwrap()));
            }
            if let Some(message) = error.get_mut("message") {
                *message = Value::String(normalize(message.as_str().unwrap()));
            }
            if GORILLA_CLOSE_TEXT.contains(&name) {
                for e in [&mut error, &mut want_error] {
                    if let Some(map) = e.as_object_mut() {
                        map.remove("message");
                    }
                }
            }
            if error != want_error {
                diffs.push(format!("error:\n  go   {want_error}\n  rust {error}"));
            }
            for (field, got) in [("frames", &recorded.frames), ("http", &recorded.http)] {
                let got: Vec<String> = got.iter().map(|g| normalize(g)).collect();
                let want: Vec<String> = turn[field]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_owned())
                    .collect();
                if got != want {
                    diffs.push(format!("{field}:\n  go   {want:#?}\n  rust {got:#?}"));
                }
            }
            let want_upgrades: Vec<String> = turn["upgrades"]
                .as_array()
                .unwrap()
                .iter()
                .map(|u| {
                    let text = u.as_str().unwrap();
                    let mut lines = text.lines();
                    let uri = lines.next().unwrap_or_default().to_owned();
                    let kept: Vec<&str> = lines
                        .filter(|l| COMPARED_HEADERS.iter().any(|h| l.starts_with(&format!("{h}: "))))
                        .collect();
                    format!("{uri}\n{}", kept.join("\n"))
                })
                .collect();
            let got_upgrades: Vec<String> = recorded.upgrades.iter().map(|u| normalize(u)).collect();
            if got_upgrades != want_upgrades {
                diffs.push(format!(
                    "upgrades:\n  go   {want_upgrades:#?}\n  rust {got_upgrades:#?}"
                ));
            }
            if !diffs.is_empty() {
                failures.push(format!("== {name} turn {i}\n{}", diffs.join("\n")));
            }
        }
        executor.close_session(session);
        server.abort();
    }
    assert!(
        failures.is_empty(),
        "{} turn(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

#[test]
fn websockets_flag_follows_go() {
    let mut c = credential("a", &serde_json::json!({}), "");
    assert!(!websockets_enabled(&c));
    c.metadata.insert("websockets".into(), Value::Bool(true));
    assert!(websockets_enabled(&c));
    c.attributes.insert("websockets".into(), "false".into());
    assert!(!websockets_enabled(&c), "a parsable attribute wins");
    c.attributes.insert("websockets".into(), "maybe".into());
    assert!(websockets_enabled(&c), "an unparsable attribute falls back to metadata");
    c.metadata.insert("websockets".into(), Value::String(" TRUE ".into()));
    assert!(websockets_enabled(&c));
    c.metadata.insert("websockets".into(), Value::from(1));
    assert!(!websockets_enabled(&c), "numbers are not bools");
}

#[test]
fn ws_url_follows_go() {
    assert_eq!(
        ws_url("https://api.x.ai/v1/responses").unwrap(),
        "wss://api.x.ai/v1/responses"
    );
    assert_eq!(
        ws_url(" HTTP://127.0.0.1:9/v1/responses ").unwrap(),
        "ws://127.0.0.1:9/v1/responses"
    );
    assert_eq!(ws_url("wss://h/x").unwrap(), "wss://h/x");
    assert_eq!(
        String::from_utf8_lossy(&ws_url("ftp://h/x").unwrap_err().body),
        r#"xai websockets executor: unsupported responses websocket URL scheme "ftp""#
    );
    assert_eq!(
        String::from_utf8_lossy(&ws_url("https:///x").unwrap_err().body),
        "xai websockets executor: responses websocket URL host is empty"
    );
}
