// Prints the three-letter codes golang.org/x/text/currency.ParseISO accepts, at the
// version CLIProxyAPI 6fecc6e uses, as the Rust table src/management/iso_currency.rs.
//
// Usage: gen.sh /absolute/path/to/CLIProxyAPI
package main

import (
	"fmt"
	"os"
	"strings"

	_ "github.com/router-for-me/CLIProxyAPI/v8/internal/api/handlers/management"
	"golang.org/x/text/currency"
)

func main() {
	var codes []string
	for a := 'A'; a <= 'Z'; a++ {
		for b := 'A'; b <= 'Z'; b++ {
			for c := 'A'; c <= 'Z'; c++ {
				code := string([]rune{a, b, c})
				if _, err := currency.ParseISO(code); err == nil {
					codes = append(codes, code)
				}
			}
		}
	}
	var out strings.Builder
	out.WriteString("//! The codes `golang.org/x/text/currency.ParseISO` accepts at the version CLIProxyAPI\n")
	out.WriteString("//! 6fecc6e uses (Go's quota summary currency check). Generated by\n")
	out.WriteString("//! tests/reference/currency/gen.sh; do not edit.\n\n")
	fmt.Fprintf(&out, "pub(super) const CODES: [&str; %d] = [\n", len(codes))
	for i := 0; i < len(codes); i += 12 {
		end := i + 12
		if end > len(codes) {
			end = len(codes)
		}
		out.WriteString("    ")
		for j, code := range codes[i:end] {
			if j > 0 {
				out.WriteString(" ")
			}
			fmt.Fprintf(&out, "%q,", code)
		}
		out.WriteString("\n")
	}
	out.WriteString("];\n")
	if err := os.WriteFile(os.Args[1], []byte(out.String()), 0o644); err != nil {
		panic(err)
	}
}
