//! Replays `fixtures/plugin_cli_go.json` (generated by `reference/plugin_cli` from Go's
//! server binary at 6fecc6e) with this binary and the same recorder plugin: plugin flags
//! registered before the parse, Go's parse errors for them, and runs handed to the
//! plugin (exit code, output, the execute request and the auth files written).

// Native plugins load only on Unix (the host's `native` module).
#![cfg(unix)]

use std::os::unix::fs::PermissionsExt as _;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use serde_json::Value;

/// The generator's `lines`: no log lines or banner; after a parse error (exit 2) only
/// the error line.
fn lines(text: &str, exit: i64) -> Vec<String> {
    let log_line = |l: &str| {
        let b = l.as_bytes();
        b.len() > 22 && b[0] == b'[' && b[5] == b'-' && b[8] == b'-' && b[11] == b' ' && b[20] == b']'
    };
    let mut out = Vec::new();
    for line in text.trim_end_matches('\n').split('\n') {
        if line.is_empty() || log_line(line) || line.starts_with("CLIProxyAPI Version:") {
            continue;
        }
        out.push(line.to_owned());
        if exit == 2 {
            break;
        }
    }
    out
}

#[test]
fn plugin_command_line_matches_go() {
    let tmp = Path::new(env!("CARGO_TARGET_TMPDIR"));
    let Some(built) = cpa_plugin::testing::built_plugins(tmp, "plugin_cli::plugin_command_line_matches_go") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/plugin_cli_go.json")).unwrap();
    let mut failures = Vec::new();
    for (index, case) in fixture["cases"].as_array().unwrap().iter().enumerate() {
        let name = case["name"].as_str().unwrap();
        let work = cpa_plugin::testing::scratch(tmp, &format!("plugin-cli-{index}"));
        let dirs = [
            ("PLUGINDIR", work.join("plugins")),
            ("RECDIR", work.join("rec")),
            ("AUTHDIR", work.join("auths")),
        ];
        for (_, dir) in &dirs {
            std::fs::create_dir_all(dir).unwrap();
        }
        std::fs::copy(built.join("recorder.so"), dirs[0].1.join("rec.so")).unwrap();
        let respond = dirs[1].1.join("respond").join("a");
        std::fs::create_dir_all(&respond).unwrap();
        for (method, key) in [
            ("command_line.register", "register"),
            ("command_line.execute", "execute"),
        ] {
            std::fs::write(respond.join(format!("{method}.json")), case[key].as_str().unwrap()).unwrap();
        }
        for (file, body) in case["auths"].as_object().into_iter().flatten() {
            let path = dirs[2].1.join(file);
            std::fs::write(&path, body.as_str().unwrap()).unwrap();
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        }
        let config = work.join("config.yaml");
        let mut text = case["config"].as_str().unwrap().to_owned();
        for (key, dir) in &dirs {
            text = text.replace(key, &dir.to_string_lossy());
        }
        std::fs::write(&config, text).unwrap();
        let args: Vec<String> = case["args"]
            .as_array()
            .unwrap()
            .iter()
            .map(|a| a.as_str().unwrap().replace("CONFIG", &config.to_string_lossy()))
            .collect();
        let mut child = Command::new(env!("CARGO_BIN_EXE_cliproxy"))
            .args(&args)
            .current_dir(&work)
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        let deadline = Instant::now() + Duration::from_secs(60);
        while child.try_wait().unwrap().is_none() {
            if Instant::now() > deadline {
                let _ = child.kill();
                panic!("case {name} did not exit");
            }
            std::thread::sleep(Duration::from_millis(20));
        }
        let output = child.wait_with_output().unwrap();
        let normalize = |s: &str| {
            let mut s = s.replace(&*config.to_string_lossy(), "CONFIG");
            for (key, dir) in &dirs {
                s = s.replace(&*dir.to_string_lossy(), key);
            }
            s.replace(&*work.to_string_lossy(), "WORK")
        };
        let exit = i64::from(output.status.code().unwrap_or(-1));
        let mut request = Value::Null;
        if let Ok(records) = std::fs::read_to_string(dirs[1].1.join("a.jsonl")) {
            for line in records.lines() {
                let rec: Value = serde_json::from_str(line).unwrap();
                if rec["method"] == "command_line.execute" {
                    request = serde_json::from_str(&normalize(rec["request"].as_str().unwrap())).unwrap();
                    request["Program"] = "PROGRAM".into();
                }
            }
        }
        let mut files = serde_json::Map::new();
        let mut names: Vec<_> = std::fs::read_dir(&dirs[2].1)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        for file in names {
            let path = dirs[2].1.join(&file);
            let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
            let body = std::fs::read_to_string(&path).unwrap();
            files.insert(file, format!("{mode:o} {body}").into());
        }
        let got = serde_json::json!({
            "exit": exit,
            "stdout": lines(&normalize(&String::from_utf8_lossy(&output.stdout)), exit),
            "stderr": lines(&normalize(&String::from_utf8_lossy(&output.stderr)), exit),
            "request": request,
            "files": files,
        });
        let mut want = case["result"].clone();
        // ponytail: an unknown flag is reported by clap, not with Go's "flag provided but
        // not defined" (the binary's documented flag-parse gap); only the exit code is
        // compared there.
        if want["stderr"][0]
            .as_str()
            .is_some_and(|l| l.starts_with("flag provided but not defined:"))
        {
            want["stderr"] = got["stderr"].clone();
        }
        if want != got {
            failures.push(format!("case {index} ({name}) {args:?}\n  go:   {want}\n  rust: {got}"));
        }
        let _ = std::fs::remove_dir_all(&work);
    }
    assert!(
        failures.is_empty(),
        "{} case(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
