//! Replays `fixtures/plugin_wiring_go.json` (generated by `reference/plugin_wiring` from
//! Go's server binary at 6fecc6e) against this binary with the same recorder plugins:
//! identical raw HTTP requests, compared on what the client gets and on the exact
//! requests the plugins receive (frontend auth so far).

// Native plugins load only on Unix (the host's `native` module).
#![cfg(unix)]

use std::io::{Read as _, Write as _};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use serde_json::{Map, Value, json};

/// The generator's upstream (`httptest.NewServer`): fixed answers by path, every request
/// recorded as Go's handler sees it (canonical headers without Host).
struct Upstream {
    url: String,
    routes: Arc<Mutex<Map<String, Value>>>,
    seen: Arc<Mutex<Vec<Value>>>,
}

/// The route for the `n`-th request to a path: `then` answers later requests in order
/// (the last repeats).
fn nth_route(route: &Value, n: usize) -> Value {
    match route["then"].as_array().filter(|t| n > 0 && !t.is_empty()) {
        Some(then) => then[n.min(then.len()) - 1].clone(),
        None => route.clone(),
    }
}

impl Upstream {
    fn start() -> Self {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let url = format!("http://{}", listener.local_addr().unwrap());
        let routes: Arc<Mutex<Map<String, Value>>> = Arc::default();
        let seen: Arc<Mutex<Vec<Value>>> = Arc::default();
        let (r, s) = (routes.clone(), seen.clone());
        std::thread::spawn(move || {
            for conn in listener.incoming() {
                let Ok(conn) = conn else { return };
                let (r, s) = (r.clone(), s.clone());
                std::thread::spawn(move || serve_upstream(conn, &r, &s));
            }
        });
        Upstream { url, routes, seen }
    }

    fn take(&self) -> Vec<Value> {
        std::mem::take(&mut *self.seen.lock().unwrap())
    }
}

/// One connection, kept alive like Go's `httptest` server: requests until EOF.
fn serve_upstream(mut conn: TcpStream, routes: &Mutex<Map<String, Value>>, seen: &Mutex<Vec<Value>>) {
    let mut raw = Vec::new();
    let mut buf = [0u8; 8192];
    loop {
        let head_end = loop {
            if let Some(i) = raw.windows(4).position(|w| w == b"\r\n\r\n") {
                break i;
            }
            match conn.read(&mut buf) {
                Ok(0) | Err(_) => return,
                Ok(n) => raw.extend_from_slice(&buf[..n]),
            }
        };
        let head = String::from_utf8_lossy(&raw[..head_end]).into_owned();
        let mut lines = head.split("\r\n");
        let mut request_line = lines.next().unwrap().split(' ');
        let (method, uri) = (
            request_line.next().unwrap().to_owned(),
            request_line.next().unwrap().to_owned(),
        );
        let mut header: std::collections::BTreeMap<String, Vec<String>> = Default::default();
        for line in lines {
            let (name, value) = line.split_once(':').unwrap();
            let name = cpa_exec::proxy::canonical_header(name.trim());
            if name != "Host" {
                header.entry(name).or_default().push(value.trim().to_owned());
            }
        }
        raw.drain(..head_end + 4);
        let chunked = header
            .get("Transfer-Encoding")
            .is_some_and(|v| v.iter().any(|v| v.eq_ignore_ascii_case("chunked")));
        let length: usize = header
            .get("Content-Length")
            .and_then(|v| v[0].parse().ok())
            .unwrap_or(0);
        let body_len = loop {
            let complete = if chunked {
                raw.windows(5).position(|w| w == b"0\r\n\r\n").map(|i| i + 5)
            } else {
                (raw.len() >= length).then_some(length)
            };
            if let Some(n) = complete {
                break n;
            }
            match conn.read(&mut buf) {
                Ok(0) | Err(_) => return,
                Ok(n) => raw.extend_from_slice(&buf[..n]),
            }
        };
        let mut body: Vec<u8> = raw.drain(..body_len).collect();
        if chunked {
            body = dechunk(&body);
            header.remove("Transfer-Encoding");
        }
        seen.lock().unwrap().push(json!({
            "method": method,
            "uri": uri,
            "header": header,
            "body": String::from_utf8_lossy(&body),
        }));
        let path = uri.split('?').next().unwrap_or_default().to_owned();
        let route = {
            let mut routes = routes.lock().unwrap();
            let served = routes.entry(format!("served {path}")).or_insert(Value::from(0u64));
            let n = served.as_u64().unwrap() as usize;
            *served = Value::from(n as u64 + 1);
            routes.get(&path).map(|r| nth_route(r, n))
        };
        let mut truncate = false;
        let reply = match route {
            None => "HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n".to_owned(),
            Some(route) => {
                let body = route["body"].as_str().unwrap_or_default();
                truncate = route["truncate"].as_bool().unwrap_or(false);
                let mut out = format!("HTTP/1.1 {} X\r\n", route["status"]);
                for (name, value) in route["headers"].as_object().into_iter().flatten() {
                    out.push_str(&format!("{name}: {}\r\n", value.as_str().unwrap()));
                }
                // A truncated answer declares more than it sends, then drops the line.
                let declared = body.len() + if truncate { 100 } else { 0 };
                out.push_str(&format!("Content-Length: {declared}\r\n\r\n{body}"));
                out
            }
        };
        if conn.write_all(reply.as_bytes()).is_err() || truncate {
            return;
        }
    }
}

struct Runner {
    work: PathBuf,
    dirs: Vec<(&'static str, PathBuf)>,
    port: u16,
    upstream: Arc<Upstream>,
    child: Child,
}

impl Runner {
    fn start(built: &Path, tmp: &Path, index: usize, scenario: &Value, upstream: Arc<Upstream>) -> Self {
        *upstream.routes.lock().unwrap() = scenario["upstream"].as_object().cloned().unwrap_or_default();
        upstream.take();
        let work = cpa_plugin::testing::scratch(tmp, &format!("plugin-wiring-{index}"));
        let dirs = vec![
            ("PLUGINDIR", work.join("plugins")),
            ("RECDIR", work.join("rec")),
            ("AUTHDIR", work.join("auths")),
        ];
        for (_, dir) in &dirs {
            std::fs::create_dir_all(dir).unwrap();
        }
        let port = TcpListener::bind("127.0.0.1:0").unwrap().local_addr().unwrap().port();
        let mut runner = Runner {
            work,
            dirs,
            port,
            upstream,
            child: Command::new("true").spawn().unwrap(),
        };
        for (file, from) in scenario["plugins"].as_object().unwrap() {
            let from = format!("{}.so", from.as_str().unwrap());
            std::fs::copy(built.join(from), runner.dir("PLUGINDIR").join(file)).unwrap();
        }
        for (file, body) in scenario["auths"].as_object().into_iter().flatten() {
            std::fs::write(
                runner.dir("AUTHDIR").join(file),
                runner.placeholders(body.as_str().unwrap()),
            )
            .unwrap();
        }
        for respond in scenario["responds"].as_array().into_iter().flatten() {
            runner.respond(respond);
        }
        let config = runner.work.join("config.yaml");
        std::fs::write(&config, runner.placeholders(scenario["config"].as_str().unwrap())).unwrap();
        let log = std::fs::File::create(runner.work.join("server.log")).unwrap();
        runner.child = Command::new(env!("CARGO_BIN_EXE_cliproxy"))
            .arg("-config")
            .arg(&config)
            .arg("-local-model")
            .current_dir(&runner.work)
            .env_clear()
            .env("HOME", &runner.work)
            .env("PATH", "/usr/bin:/bin")
            .env("TZ", "UTC")
            .stdout(Stdio::from(log.try_clone().unwrap()))
            .stderr(Stdio::from(log))
            .spawn()
            .unwrap();
        let deadline = Instant::now() + Duration::from_secs(60);
        loop {
            if let Ok(res) = runner.http(&json!({"method": "GET", "path": "/healthz"}))
                && res["status"] == 200
            {
                return runner;
            }
            if Instant::now() > deadline || runner.child.try_wait().unwrap().is_some() {
                let log = std::fs::read_to_string(runner.work.join("server.log")).unwrap_or_default();
                panic!("{}: server not ready\n{log}", scenario["name"]);
            }
            std::thread::sleep(Duration::from_millis(50));
        }
    }

    fn dir(&self, key: &str) -> &Path {
        &self.dirs.iter().find(|(k, _)| *k == key).unwrap().1
    }

    fn placeholders(&self, s: &str) -> String {
        let mut s = s
            .replace("PORT", &self.port.to_string())
            .replace("UPSTREAM", &self.upstream.url);
        for (key, dir) in &self.dirs {
            s = s.replace(key, &dir.to_string_lossy());
        }
        s
    }

    fn normalize(&self, s: &str) -> String {
        let mut s = s
            .replace(&self.upstream.url, "UPSTREAM")
            .replace(self.upstream.url.trim_start_matches("http://"), "UPSTREAMHOST");
        for (key, dir) in &self.dirs {
            s = s.replace(&*dir.to_string_lossy(), key);
        }
        s.replace(&*self.work.to_string_lossy(), "WORK")
            .replace(&format!("127.0.0.1:{}", self.port), "127.0.0.1:PORT")
    }

    fn respond(&self, args: &Value) {
        let dir = self.dir("RECDIR").join("respond").join(args["label"].as_str().unwrap());
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(format!("{}.json", args["method"].as_str().unwrap()));
        match args["envelope"].as_str().unwrap_or_default() {
            "" => {
                let _ = std::fs::remove_file(path);
            }
            envelope => std::fs::write(path, self.placeholders(envelope)).unwrap(),
        }
    }

    /// The generator's `raw`: one HTTP/1.1 request with exactly these header lines; the
    /// reply's headers as Go's `ReadResponse` keeps them (canonical names, values joined
    /// by newlines) minus the varying ones.
    fn http(&self, args: &Value) -> std::io::Result<Value> {
        let mut conn = TcpStream::connect(("127.0.0.1", self.port))?;
        conn.set_read_timeout(Some(Duration::from_secs(30)))?;
        let method = args["method"].as_str().unwrap();
        let body = self.placeholders(args["body"].as_str().unwrap_or_default());
        let mut head = format!(
            "{method} {} HTTP/1.1\r\nHost: cpa.test\r\n",
            self.placeholders(args["path"].as_str().unwrap())
        );
        for pair in args["headers"].as_array().into_iter().flatten() {
            let value = self.placeholders(pair[1].as_str().unwrap());
            head.push_str(&format!("{}: {value}\r\n", pair[0].as_str().unwrap()));
        }
        if !body.is_empty() || method == "POST" {
            head.push_str(&format!("Content-Length: {}\r\n", body.len()));
        }
        head.push_str("Connection: close\r\n\r\n");
        conn.write_all(head.as_bytes())?;
        conn.write_all(body.as_bytes())?;
        let mut raw = Vec::new();
        conn.read_to_end(&mut raw)?;
        let split = raw
            .windows(4)
            .position(|w| w == b"\r\n\r\n")
            .ok_or(std::io::ErrorKind::UnexpectedEof)?;
        let head = String::from_utf8_lossy(&raw[..split]).into_owned();
        let mut body = raw[split + 4..].to_vec();
        let mut lines = head.split("\r\n");
        let status: u16 = lines.next().unwrap().split(' ').nth(1).unwrap().parse().unwrap();
        let mut headers: Map<String, Value> = Map::new();
        let mut chunked = false;
        for line in lines {
            let (name, value) = line.split_once(':').unwrap();
            let name = cpa_exec::proxy::canonical_header(name.trim());
            let value = value.trim();
            if name == "Transfer-Encoding" {
                chunked = value.eq_ignore_ascii_case("chunked");
                continue;
            }
            if matches!(name.as_str(), "Date" | "Content-Length" | "Connection" | "Keep-Alive") {
                continue;
            }
            let value = if name == "X-Cpa-Trace-Id" {
                "SET".to_owned()
            } else {
                self.normalize(value)
            };
            match headers.get_mut(&name) {
                Some(Value::String(existing)) => {
                    existing.push('\n');
                    existing.push_str(&value);
                }
                _ => {
                    headers.insert(name, value.into());
                }
            }
        }
        if chunked {
            body = dechunk(&body);
        }
        let mut sorted: Vec<_> = headers.into_iter().collect();
        sorted.sort_by(|a, b| a.0.cmp(&b.0));
        Ok(json!({
            "status": status,
            "headers": Map::from_iter(sorted),
            "body": self.normalize(&String::from_utf8_lossy(&body)),
        }))
    }

    /// The generator's `records`: every call a recorder received whose method is listed
    /// (a trailing "." matches a prefix), files in name order, then cleared.
    fn records(&self, args: &Value) -> Value {
        let methods: Vec<&str> = args["methods"]
            .as_array()
            .unwrap()
            .iter()
            .map(|m| m.as_str().unwrap())
            .collect();
        let wanted = |m: &str| {
            methods
                .iter()
                .any(|w| *w == m || (w.ends_with('.') && m.starts_with(w)))
        };
        let mut names: Vec<String> = std::fs::read_dir(self.dir("RECDIR"))
            .unwrap()
            .map(|e| e.unwrap())
            .filter(|e| e.file_type().unwrap().is_file())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        let mut out = Vec::new();
        for name in names {
            let path = self.dir("RECDIR").join(&name);
            let data = std::fs::read_to_string(&path).unwrap();
            std::fs::remove_file(&path).unwrap();
            for line in data.lines() {
                let Ok(rec) = serde_json::from_str::<Value>(line) else {
                    continue;
                };
                let method = rec["method"].as_str().unwrap_or_default();
                if !wanted(method) {
                    continue;
                }
                let request = mask_varying(&callback_ids(&self.normalize(rec["request"].as_str().unwrap())));
                out.push(json!({
                    "label": name.trim_end_matches(".jsonl"),
                    "method": method,
                    "request": request,
                }));
            }
        }
        Value::Array(out)
    }
}

impl Drop for Runner {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
        let _ = std::fs::remove_dir_all(&self.work);
    }
}

/// The generator's `varying` and `maskCreated`: per-request IDs and timestamps become
/// `#`; model-list registration times inside base64 bodies become 0.
fn mask_varying(s: &str) -> String {
    let mut out = s.to_owned();
    for key in [
        "RequestID",
        "TraceID",
        "StartedAt",
        "CompletedAt",
        "selected_auth_id",
        "selected_auth_index",
        "RequestedAt",
        "AuthID",
        "AuthIndex",
    ] {
        out = mask_string_values(&out, &format!("\"{key}\":\""));
    }
    for key in ["Latency", "TTFT"] {
        out = mask_number(&out, &format!("\"{key}\":"));
    }
    let marker = "\"Body\":\"";
    let mut result = String::new();
    let mut rest = out.as_str();
    while let Some(at) = rest.find(marker) {
        let after = &rest[at + marker.len()..];
        let end = after.find('"').unwrap_or(after.len());
        let field = &after[..end];
        result.push_str(&rest[..at + marker.len()]);
        match base64_decode(field) {
            Some(raw) if !field.is_empty() => {
                let text = String::from_utf8_lossy(&raw).into_owned();
                result.push_str(&base64_encode(mask_created(&text).as_bytes()));
            }
            _ => result.push_str(field),
        }
        rest = &after[end..];
    }
    result.push_str(rest);
    result
}

/// `"<key>":"<anything>"` (non-empty) becomes `"<key>":"#"`.
fn mask_string_values(s: &str, key: &str) -> String {
    let mut out = String::new();
    let mut rest = s;
    while let Some(at) = rest.find(key) {
        let after = &rest[at + key.len()..];
        let end = after.find('"').unwrap_or(after.len());
        out.push_str(&rest[..at + key.len()]);
        out.push_str(if end == 0 { "" } else { "#" });
        rest = &after[end..];
    }
    out.push_str(rest);
    out
}

fn mask_created(s: &str) -> String {
    mask_number(s, "\"created\":")
}

/// `<key><digits>` becomes `<key>0`.
fn mask_number(s: &str, key: &str) -> String {
    let mut out = String::new();
    let mut rest = s;
    while let Some(at) = rest.find(key) {
        let after = &rest[at + key.len()..];
        let digits = after.bytes().take_while(u8::is_ascii_digit).count();
        out.push_str(&rest[..at + key.len()]);
        out.push_str(if digits > 0 { "0" } else { "" });
        rest = &after[digits..];
    }
    out.push_str(rest);
    out
}

const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

fn base64_encode(data: &[u8]) -> String {
    let mut out = String::new();
    for chunk in data.chunks(3) {
        let n = chunk
            .iter()
            .enumerate()
            .fold(0u32, |n, (i, b)| n | u32::from(*b) << (16 - 8 * i));
        for i in 0..4 {
            if i <= chunk.len() {
                out.push(B64[(n >> (18 - 6 * i) & 63) as usize] as char);
            } else {
                out.push('=');
            }
        }
    }
    out
}

fn base64_decode(text: &str) -> Option<Vec<u8>> {
    let mut out = Vec::new();
    let bytes: Vec<u8> = text.bytes().filter(|&b| b != b'=').collect();
    for chunk in bytes.chunks(4) {
        let mut n = 0u32;
        for (i, b) in chunk.iter().enumerate() {
            n |= (B64.iter().position(|c| c == b)? as u32) << (18 - 6 * i);
        }
        for i in 0..chunk.len().saturating_sub(1) {
            out.push((n >> (16 - 8 * i)) as u8);
        }
    }
    Some(out)
}

/// `"host_callback_id":"<digits>"` becomes `"host_callback_id":"#"`.
fn callback_ids(s: &str) -> String {
    const KEY: &str = "\"host_callback_id\":\"";
    let mut out = String::new();
    let mut rest = s;
    while let Some(at) = rest.find(KEY) {
        let after = &rest[at + KEY.len()..];
        let digits = after.bytes().take_while(u8::is_ascii_digit).count();
        if digits > 0 && after[digits..].starts_with('"') {
            out.push_str(&rest[..at]);
            out.push_str(KEY);
            out.push('#');
            rest = &after[digits..];
        } else {
            out.push_str(&rest[..at + KEY.len()]);
            rest = after;
        }
    }
    out.push_str(rest);
    out
}

fn dechunk(mut raw: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    loop {
        let Some(end) = raw.windows(2).position(|w| w == b"\r\n") else {
            return out;
        };
        let size = std::str::from_utf8(&raw[..end])
            .unwrap()
            .split(';')
            .next()
            .unwrap()
            .trim();
        let size = usize::from_str_radix(size, 16).unwrap();
        if size == 0 {
            return out;
        }
        out.extend_from_slice(&raw[end + 2..end + 2 + size]);
        raw = &raw[end + 2 + size + 2..];
    }
}

#[test]
fn request_path_plugins_match_go() {
    let tmp = Path::new(env!("CARGO_TARGET_TMPDIR"));
    let Some(built) = cpa_plugin::testing::built_plugins(tmp, "plugin_wiring::request_path_plugins_match_go") else {
        return;
    };
    let fixture: Value = serde_json::from_str(include_str!("fixtures/plugin_wiring_go.json")).unwrap();
    let mut failures = Vec::new();
    let upstream = Arc::new(Upstream::start());
    for (index, scenario) in fixture["scenarios"].as_array().unwrap().iter().enumerate() {
        let name = scenario["name"].as_str().unwrap();
        let runner = Runner::start(built, tmp, index, scenario, upstream.clone());
        for (n, step) in scenario["steps"].as_array().unwrap().iter().enumerate() {
            let got = match step["op"].as_str().unwrap() {
                "respond" => {
                    runner.respond(&step["args"]);
                    continue;
                }
                "sleep" => {
                    std::thread::sleep(Duration::from_millis(step["args"].as_u64().unwrap()));
                    continue;
                }
                "http" => runner.http(&step["args"]).unwrap(),
                "records" => runner.records(&step["args"]),
                "upstream" => {
                    let seen = runner.upstream.take();
                    serde_json::from_str(&runner.normalize(&serde_json::to_string(&seen).unwrap())).unwrap()
                }
                op => panic!("unknown op {op}"),
            };
            if got != step["result"] {
                failures.push(format!(
                    "{name} step {n} {}\n  go:   {}\n  rust: {got}",
                    step["args"], step["result"]
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} step(s) differ from Go:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
